const TRANSLATIONS = {
    "JOIN": "参加",
    "welcome to TETR.IO": "TETR.IOへようこそ",
    "puzzle together in this modern yet familiar online stacker. play against friends and foes all over the world, or claim a spot on the leaderboards - the stacker future is yours!": "モダンでありながら親しみやすいオンラインスタッカーで、パズルを楽しみましょう。世界中のライバルと対戦したり、リーダーボードの上位を目指しましょう。スタッカーの未来はあなたの手に！",
    "enter a username to join, or leave it blank to get a random one": "ユーザー名を入力して参加するか、空欄のままにしてランダムな名前を取得します",
    "TETR.IO is in ALPHA. please report bugs when you see them!": "TETR.IOはアルファ版です。バグを見つけた場合は報告をお願いします！",
    "by joining, you accept the ": "参加することで、以下に同意したとみなされます: ",
    "terms of use": "利用規約",
    // "privacy policy": "プライバシーポリシー",
    // " and ": " および ",
    // "rules": "ルール",
    "PLAY": "プレイ",
    "TETRA CHANNEL": "TETRA CHANNEL",
    "NEW!": "NEW!",
    "ABOUT": "TETR.IOについて",
    "total players": "総プレイヤー数",
    "games played": "総プレイゲーム数",
    "hours played": "総プレイ時間",
    "good to see you again!": "おかえりなさい！",
    "BACK": "戻る",
    "I'M NOT MULTIACCOUNTING": "複垢（サブアカウント）ではありません",
    "I FORGOT": "パスワードをお忘れの方",
    "LOGIN": "ログイン",
    "password incorrect": "パスワードが正しくありません",
    "PASSWORD": "パスワード",
    "want to join?": "参加しますか？",
    "the nickname ": "ユーザー名「",
    " hasn't been registered. do you want to claim it as yours, or play anonymously? you won't be able to submit scores to the leaderboards or play in matchmaking when anonymous.": "」はまだ登録されていません。この名前を登録してプレイしますか？それとも匿名でプレイしますか？匿名プレイの場合、スコアの記録やマッチメイキングへの参加はできません。",
    "stay ANONYMOUS": "匿名のままプレイ",
    "let's make things official": "アカウントを登録する",
    "to register, please choose a password for yourself": "登録を完了するには、パスワードを設定してください",
    "password must be at least 6 characters": "パスワードは6文字以上で入力してください",
    "those passwords don't match": "パスワードが一致しません",
    "just to be sure…": "確認のため…",
    "please enter the characters above": "表示されている文字を入力してください",
    "if the email you entered was correct, you should be receiving an email shortly!": "入力されたメールアドレスが正しければ、まもなく確認メールが届きます！",
    "ANONYMOUS USERS CANNOT SET RECORDS": "匿名ユーザーは記録を保存できません",
    "ANONYMOUS USERS MAY NOT ENTER TETRA LEAGUE": "匿名ユーザーはTETRA LEAGUEに参加できません",
    "Ǳ VIEW FULL": "Ǳ 全体を表示",
    "expert quick play": "エキスパート クイックプレイ",
    "EXPERT QUICK PLAY": "エキスパート クイックプレイ",
    "WORLD": "世界",
    "KOREA, REPUBLIC OF": "大韓民国",
    "FRIENDS": "フレンド",
    "Ǳ MY PAGE": "Ǳ マイページ",
    "GET READY FOR": "次のバトルに向けて",
    "THE NEXT BATTLE": "準備を整えましょう",
    "RECENT": "最近のプレイ",
    "view your achievements!": "獲得した実績を確認する",
    "view other players and their achievements!": "他のプレイヤーと実績を確認する",
    "fetching records…": "記録を取得中…",
    "fetching replay…": "リプレイを取得中…",
    "FINAL TIME": "タイム",
    "replay id:": "リプレイID:",
    "opening replay": "リプレイを読み込み中",
    "FINAL SCORE": "最終スコア",
    "STATS": "統計",
    "OVERVIEW": "概要",
    "FULL": "詳細",
    "レベル": "レベル",
    "PIECES PLACED": "設置ミノ数",
    "PIECES per SECOND": "PPS (ミノ/秒)",
    "KEYS PRESSED": "打鍵数",
    "KEYS per PIECE": "KPP (キー/ミノ)",
    "KEYS per SECOND": "KPS (キー/秒)",
    "HOLDS": "ホールド回数",
    "SCORE": "スコア",
    "TIME": "時間",
    "LINES": "ライン数",
    "LINES per MINUTE": "LPM (ライン/分)",
    "maximum COMBO": "最大コンボ",
    "maximum back-to-back chain": "最大B2Bチェーン",
    "ALL CLEARS": "オールクリア",
    "finesse %": "フィネス精度 %",
    "finesse faults": "フィネスミス数",
    "SINGLES": "シングル",
    "DOUBLES": "ダブル",
    "TRIPLES": "トリプル",
    "QUADS": "クアッド (テトリス)",
    "T-spin MINIS": "Tスピン ミニ",
    "T-spin MINI SINGLES": "Tスピン ミニシングル",
    "T-spin SINGLES": "Tスピン シングル",
    "T-spin MINI DOUBLES": "Tスピン ミニダブル",
    "T-spin DOUBLES": "Tスピン ダブル",
    "T-spin TRIPLES": "Tスピン トリプル",
    "REPLAY": "リプレイ",
    "watching ": "観戦中: ",
    " play ": " プレイ中: ",
    "finesse piece": "個のフィネスミノ",
    "finesse pieces": "個のフィネスミノ",
    "only the first 100 are shown. to see the full leaderboard, click VIEW FULL above.": "上位100名のみ表示されています。ランキング全体を見るには「全体を表示」をクリックしてください。",
    "top the global leaderboards!": "世界ランキングのトップを目指そう！",
    "TETRA CHANNEL / LEADERBOARDS": "TETRA CHANNEL / リーダーボード",
    "TETRA CHANNEL / PLAYERS": "TETRA CHANNEL / プレイヤー",
    "TETRA CHANNEL / ME": "TETRA CHANNEL / マイページ",
    "track your progression!": "自分の上達状況を確認しよう！",
    "BY LEAGUE RATING": "リーグレーティング順",
    "BY ACHIEVEMENT RATING": "実績レーティング順",
    "BY XP": "XP順",
    "fetching players…": "プレイヤー情報を取得中…",
    "glicko: ": "Glicko値: ",
    "email (optional)": "メールアドレス (任意)",
    "PASSWORD AGAIN": "パスワード (再入力)",
    "REGISTER": "登録する",
    "username must be 3-16 characters long and only consist of letters, numbers, dashes and underscores": "ユーザー名は3〜16文字の英数字、ハイフン、アンダースコアのみ使用可能です",
    "forgot your password?": "パスワードをお忘れですか？",
    "if you have an email address associated with your account, you can reset your password by entering your email.": "アカウントに登録されたメールアドレスを入力すると、パスワードリセット用の案内が送信されます。",
    "you must enter a valid email address": "有効なメールアドレスを入力してください",
    "email": "メールアドレス",
    "REQUEST RESET": "リセットメールを送信",
    "WHAT'S NEW": "更新情報",
    "ALL PATCH NOTES": "すべてのパッチノート",
    "COOL!": "OK!",
    "welcome back to TETR.IO!": "TETR.IOへおかえりなさい！",
    "LOG OUT": "ログアウト",
    "is this you?": "このユーザー名で間違いありませんか？",
    "MULTIPLAYER": "マルチプレイヤー",
    "NEW GAMEMODE!!": "新ゲームモード!!",
    "play online with friends and foes": "オンラインで世界中のプレイヤーと対戦しよう",
    "SOLO": "ソロモード",
    "HOME": "ホーム",
    "challenge yourself and top the leaderboards": "ハイスコアに挑みランキングの上位を目指そう",
    "leaderboards, replays and more": "リーダーボード、リプレイなど",
    "leaderboards, achievements, replays and more": "リーダーボード、実績、リプレイなど",
    "CONFIG": "設定",
    "connected to server": "サーバーに接続完了",
    "enter room id or url and hit enter...": "部屋のIDまたはURLを入力してEnterを押してください…",
    "TETRA LEAGUE": "TETRA LEAGUE",
    "PEOPLE": "ソーシャル",
    "In Menus ": "メニュー画面",
    " In Menus": "メニュー画面",
    "Ǖ find someone…": "Ǖ プレイヤーを検索…",
    "YOU ARE SILENCED": "ミュート状態です",
    "Stop spamming or you will be silenced!": "スパム行為をやめてください。続けた場合ミュート処理されます！",
    " ONLINE": " オンライン",
    "appear as usual": "通常どおり表示",
    " AWAY": " 離席中",
    "appear away, unless you're offline or busy": "オフラインまたはビジー状態でない限り「離席中」と表示",
    " BUSY": " 取り込み中",
    "appear busy, unless you're offline. receive no notifications. always enabled in TETRA LEAGUE (unless you're invisible)": "「取り込み中」と表示し通知をオフにします（TETRA LEAGUEプレイ中は自動で有効化されます）",
    " INVISIBLE": " 居留守 (オフライン表示)",
    "appear offline at all times": "常にオフラインとして表示します",
    "ONLINE": "オンライン",
    "ALL": "すべて",
    "OTHER": "その他",
    "BLOCKED": "ブロック済み",
    "Nobody's online right now.": "現在オンラインのフレンドはいません。",
    "Not connected to online servers. Sit tight, we'll try to reconnect you in the background.": "サーバーから切断されました。バックグラウンドで自動再接続を行っています…",
    "Notifications will appear here.": "通知はここに表示されます。",
    "You haven't added any friends yet. Click the FRIEND button on a profile to friend them.": "まだフレンドがいません。プロフィール画面から「FRIEND」を押して追加してみましょう！",
    "If someone outside of your friends list messages you, they'll appear here.": "フレンド以外からのダイレクトメッセージはここに表示されます。",
    "You haven't blocked anyone yet.": "ブロックしているユーザーはいません。",
    "NOTIFICATIONS": "通知",
    "You forfeited a ranked match": "ランクマッチを途中棄権しました",
    "You have been awarded a loss for this match. Please ensure you have the time and internet connection to play! Repeated forfeits are punished (and will be automatically punished in the future). Thank you for understanding!": "このマッチは不戦敗として処理されました。プレイする際は時間に余裕を持ち、安定した回線環境で参加してください。切断や途中棄権を繰り返すとペナルティが科されます。",
    "pick a game mode": "ゲームモードを選択",
    "fight players of your skill in ranked duels": "実力の近いプレイヤーと1v1のランクマッチで戦おう",
    "QUICK PLAY": "クイックプレイ",
    "jump into a currently ongoing match": "開催中のカジュアルな大人数対戦に飛び込もう",
    "scale the tower! how far can you get?": "無限のタワーを登れ！どこまで辿り着けるか？",
    "scale the tower!": "タワーを登り詰めろ！",
    "EVENT": "イベント",
    "welcome to the ZENITH TOWER! send lines and KO enemies to scale the tower.": "ZENITH TOWERへようこそ！ラインを送り敵をKOしてタワーを登りましょう。",
    "the further up the tower, the stronger the opponents!": "上に登れば登るほど、強力な敵が待ち受けています！",
    "leaderboards reset every week, how far can you get?": "リーダーボードは毎週リセットされます。限界に挑戦しましょう！",
    "THIS WEEK'S PERSONAL BEST": "今週の自己ベスト",
    "THIS WEEK'S PERSONAL RANK": "今週の個人順位",
    "ADD OR REMOVE MODS": "MODの追加 / 削除",
    "EXPERT MODE": "エキスパートモード",
    "a less lenient challenge, for those who dare": "手加減なしの高難易度チャレンジ",
    "reach floor 9 to unlock": "9階到達でアンロック",
    "DOUBLE HOLE GARBAGE": "ダブルホールおじゃま",
    "garbage may sometimes spawn with two holes": "穴が2つ開いたおじゃまラインが発生するようになります",
    "receive double the garbage, cancel double the garbage": "おじゃま受ける量も相殺（相殺打ち消し）量も2倍になります",
    "reach floor 5 to unlock": "5階到達でアンロック",
    "gravity scales up harshly by floor": "階層が進むごとに落下速度が激増します",
    "reach floor 4 to unlock": "4階到達でアンロック",
    "NO HOLD": "ホールド禁止",
    "hold piece is disabled": "ホールド機能が使用不能になります",
    "reach floor 2 to unlock": "2階到達でアンロック",
    "MESSIER GARBAGE": "ばらばらおじゃま",
    "garbage is significantly messier": "おじゃまラインの穴の位置がよりランダムになります",
    "reach floor 3 to unlock": "3階到達でアンロック",
    "INVISIBLE": "ステルス (透明化)",
    "non-garbage minos are only visible once every five seconds": "自分が置いたミノが5秒に1回しか見えなくなります",
    "reach floor 7 to unlock": "7階到達でアンロック",
    "all-spins are rewarded, but doing the same clear twice is penalized": "全スピンでボーナスを得られますが、同じ消し方を連続で行うとペナルティが発生します",
    "reach floor 8 to unlock": "8階到達でアンロック",
    "DUO": "デュオ (2人協力)",
    "scale the tower together with someone you hold close": "パートナーと共に協力してタワーを登りましょう",
    "SNOWBALL BOARD": "スノーボールボード",
    "start with a 4x4 board, then roll it larger and larger": "4x4の狭い盤面から始まり、徐々に拡大していきます",
    "SNOWBALL": "スノーボール",
    "READY": "準備完了",
    "READY!": "準備完了！",
    "WAITING": "待機中",
    "waiting for player": "対戦相手を待っています",
    "CLICK TO INVITE A FRIEND": "クリックしてフレンドを招待",
    "reset": "リセット",
    "YOUR FINAL ALTITUDE": "最終到達高度",
    "FINAL ALTITUDE": "最終高度",
    "THIS WEEK'S COUNTRY RANK": "今週の国内順位",
    "THIS WEEK'S GLOBAL RANK": "今週の世界順位",
    "SEND TO CHAT": "チャットに送信",
    "FLOOR": "階",
    "KO's": "KO数",
    "average CLIMB SPEED": "平均上昇速度",
    "peak CLIMB SPEED": "最高上昇速度",
    "ALTITUDE per SECOND": "高度/秒",
    "ATTACK": "アタック (火力量)",
    "ATTACK per PIECE": "APP (アタック/ミノ)",
    "ATTACK per MINUTE": "APM (アタック/分)",
    "VERSUS SCORE": "VSスコア",
    "spin ZEROES": "スピン 0ライン消し",
    "spin MINIS": "スピン ミニ",
    "spin MINI SINGLES": "スピン ミニシングル",
    "spin SINGLES": "スピン シングル",
    "spin MINI DOUBLES": "スピン ミニダブル",
    "spin DOUBLES": "スピン ダブル",
    "spin MINI TRIPLES": "スピン ミニトリプル",
    "spin TRIPLES": "スピン トリプル",
    "spin MINI QUADS": "スピン ミニクアッド",
    "spin QUADS": "スピン クアッド",
    "you shouldn't do yourself that sort of injustice": "自分をそこまで追い詰める必要はありませんよ。",
    "CUSTOM GAME": "カスタムゲーム",
    "create public and private rooms to play by your rules": "自作ルールで遊べるパブリック/プライベートルームを作成",
    "ROOM LISTING": "ルーム一覧",
    "join public custom games": "公開されているカスタムルームに参加",
    "join public games": "公開ゲームに参加",
    "ROYALE": "ロイヤル",
    "face off against the best in a single lobby shared by all!": "全員が集う単一ロビーで猛者たちに挑もう！",
    " - games won: ": " - 勝利数: ",
    "FINDING MATCH": "対戦相手を探しています",
    "MATCH FOUND": "マッチングしました",
    "JOINING MATCH": "マッチに参加中",
    "getting ready to spectate…": "観戦の準備中…",
    "leaving room…": "部屋を退出中…",
    "joining game…": "ゲームに参加中…",
    "following ": "フォロー中: ",
    "waiting for ": "待機中: ",
    "free": "フリー",
    "FT3": "3勝先取 (FT3)",
    "FT5": "5勝先取 (FT5)",
    "FT7": "7勝先取 (FT7)",
    ", round ": ", ラウンド ",
    "FINISH!": "決着!",
    "FINISH": "終了",
    "ABORTED!": "無効試合!",
    "MATCH POINT": "マッチポイント",
    "TIEBREAKER": "タイブレイカー (最終決戦)",
    "DEUCE": "デュース",
    "IN QUEUE -": "待機列 -",
    "IN GAME": "試合中",
    "estimated queue time:": "予想待ち時間:",
    "SECONDS": "秒",
    "ENTER MATCHMAKING": "マッチメイキングに参加",
    "LEAVING EARLY IS PUNISHED": "途中退室にはペナルティがあります",
    "HOW DOES IT WORK?": "TETRA LEAGUEのルール",
    "Ǳ LEADERBOARDS": "Ǳ リーダーボード",
    "enter matchmaking and you will be matched up with a player of similar skill in a game of 1v1 VERSUS.": "マッチメイキングを行うと、実力の近いプレイヤーと1v1のガチンコ勝負でマッチングされます。",
    "win games to gain TR and rank up! you must play at least 10 games to see your TR. to get a RANK and enter the GLOBAL LEADERBOARDS, keep playing consistently.": "勝利してTRを稼ぎランクを上げましょう！10試合プレイするとTRが表示されます。公式ランクを取得し世界ランキングに載るには定期的なプレイが必要です。",
    "if you leave the game early at any point, you will be awarded a loss. go conquer the ranks!": "試合中に途中退出した場合、不戦敗となります。トップランクを目指して突き進みましょう！",
    "if you leave the game early at any point, you must rejoin immediately or you will be penalized. go conquer the ranks!": "切断された場合はすぐに再接続してください。再接続しない場合ペナルティ対象となります。",
    "CANCEL MATCHMAKING": "マッチメイキングをキャンセル",
    "leaving matchmaking…": "マッチメイキングをキャンセル中…",
    "face off against others and rise up through the ranks!": "ライバル達を倒し、最上のランクへ駆け登れ！",
    "switching server…": "サーバー切替中…",
    "server switched": "サーバーを切り替えました",
    "GAME IN PROGRESS, GOOD LUCK!": "試合が始まりました。ご健闘を！",
    "WAITING FOR PLAYERS": "プレイヤーを待っています",
    "PLAYERS (": "参加プレイヤー (",
    "CHAT": "チャット",
    "Please remember to be civil to your opponent.": "対戦相手へのマナーと敬意を忘れずにプレイしましょう。",
    "TETRA LEAGUE STANDING": "TETRA LEAGUE 順位",
    "TETRA LEAGUE / RESULTS": "TETRA LEAGUE / リザルト",
    "DEFEAT": "敗北",
    "VICTORY": "勝利",

    "PUBLIC ROOM": "公開ルーム",
    "create a public room anyone can join": "誰でも参加できるルームを作成します",
    "PRIVATE ROOM": "非公開ルーム",
    "create a private room for you and friends": "フレンドと遊ぶためのパスワード付きルームを作成します",
    "MULTIPLAYER / ROOM LISTING": "マルチプレイヤー / ルーム一覧",
    "REFRESH": "更新",
    "anons allowed: ": "匿名参加: ",
    ", unranked allowed: ": ", アンランク参加: ",
    " INGAME - ": " 試合中 - ",
    " LOBBY -  ": " ロビー - ",
    " and below -  ": " 以下限定 - ",
    "YES": "許可",
    "NO": "禁止",
    "pick a room to join!": "参加する部屋を選んでください！",
    "CURRENTLY INGAME": "試合進行中",
    "SPECTATE": "観戦",
    "grid": "グリッド表示",
    "OR": "または",
    "ZEN": "ZEN (練習・リラックス)",
    "EXIT": "退室",
    "left the room": "が退室しました。",
    "disconnected": "の接続が切断されました。",
    "joined the room": "が入室しました。",
    "ANON": "匿名",
    "40 LINES": "40 LINES",
    "complete 40 lines as quickly as possible": "40ラインを消す最速タイムを競います",
    "BLITZ": "BLITZ",
    "a two-minute race against the clock": "制限時間2分間のスコアタレース",
    "get as many points as possible within 2 minutes!": "2分間で最高スコアを目指しましょう！",
    "clear lines to level up and gain more points and speed!": "ラインを消してレベルを上げ、さらに多くのポイントを獲得しましょう！",
    "TWO-MINUTE BLITZ": "2分間スコアアタック",
    "relax or train in this neverending mode": "ゲームオーバーのない無限モードでリラックス・練習",
    "CUSTOM": "カスタム",
    "play, train and experiment by your rules": "ルールを自由に設定してプレイ・検証",
    "welcome to TETRA CHANNEL!": "TETRA CHANNELへようこそ！",
    "enter replay id, url or username and hit enter...": "リプレイID、URL、ユーザー名を入力してEnter…",
    "VISIT THE TETRA CHANNEL SITE": "TETRA CHANNEL サイトへアクセス",
    "VIEW FULL LEADERBOARDS, COUNTRY LEADERBOARDS, USER PAGES AND MORE": "グローバル/国別ランキング、ユーザー詳細ページをWebで確認",
    "LEADERBOARDS": "リーダーボード",
    "GLOBAL LEADERBOARDS FOR 40 LINES AND BLITZ": "40 LINES & BLITZ グローバルランキング",
    "GLOBAL LEADERBOARDS FOR 40 LINES, BLITZ AND QUICK PLAY": "40 LINES、BLITZ、QUICK PLAY グローバルランキング",
    "ME": "マイページ",
    "VIEW YOUR OWN RECORDS AND RECENT GAMES": "自身の記録や最近のプレイ履歴を確認",
    "PLAYERS": "プレイヤー",
    "TETRA LEAGUE LEADERBOARDS AND XP": "TETRA LEAGUE ランキングとXP",
    "ACHIEVEMENTS": "実績",
    "VIEW YOUR ACHIEVEMENTS AND THEIR PROGRESS": "獲得した実績と進捗状況を表示",
    "TETRA CHANNEL / ACHIEVEMENTS": "TETRA CHANNEL / 実績",
    "view your achievement progress!": "実績の獲得状況をチェック！",
    "select a slot to feature an achievement on your profile": "プロフィールに飾る実績のスロットを選択してください",
    "select an achievement to feature it, or select the slot again to cancel": "表示したい実績を選択するか、もう一度スロットを押して解除します",

    "POWERLEVELLING": "パワーレベリング",
    "XP gained": "獲得した累計XP",
    "No skill without experience.": "経験無くして成長なし。",
    "GARBAGE ATTACKER": "おじゃまアタッカー",
    "Garbage Attacker": "おじゃまアタッカー",
    "Keep up the pressure.": "プレッシャーを与え続けろ。",
    "GARBAGE OFFENSIVE": "猛攻のおじゃま",
    "Garbage Offensive": "猛攻のおじゃま",
    "lines sent": "送り出したライン数",
    "The act of violence and communication of spirit.": "攻撃こそが最大の意思表示。",
    "STACKER": "スタッカー",
    "Stacker": "スタッカー",
    "pieces placed": "設置した総ミノ数",
    "Greater than the sum of its parts?": "一つ一つの積載が大きな成果を生む。",
    "ELEGANCE": "エレガンス",
    "Elegance": "エレガンス",
    "pieces placed with perfect finesse": "ノーミス(フィネス100%)で設置したミノ数",
    "Path of least resistance.": "最も無駄のない最短のルート。",
    "CHAMPION OF THE LOBBY": "ロビーの覇者",
    "largest room to rank first place in": "1位を獲得した最大のルーム人数",
    "Biggest fish in a big pond.": "大勢の中で掴み取った頂点。",
    "SECRET GRADE": "シークレットグレード",
    "ISSUE #": "発行 #",
    "A (poorly guarded) secret.": "（誰もが知っている）秘密のパターン。",
    "20TSD": "20 TSD",
    "Clear 40 LINES using only T-Spin Doubles": "Tスピンダブル(TSD)のみで40 LINESをクリア",
    "The ancient tradition of six pieces, all placed to serve the needs of one.": "1つのTミノのために捧げられる6つのミノの伝統美。",
    "SPRINTER": "スプリンター",
    "Sprinter": "スプリンター",
    "40 LINES games completed": "40 LINESを完走した回数",
    "Don't reset.": "やり直すな、走り切れ。",
    "DETAIL ORIENTED": "効率重視",
    "Clear 40 LINES using as few inputs as possible": "最小限のキー操作打数で40 LINESをクリア",
    "Theoretically efficient can quickly become gloriously impractical.": "理論上の最小打数は、ときに異次元の難易度を誇る。",
    "ALL THE SINGLE LINES": "シングル消しの達人",
    "Clear 40 LINES using only Singles": "シングル消しのみで40 LINESをクリア",
    "Death by exactly 40 cuts.": "正確に40回切り刻んで勝ち取った勝利。",
    "1-8 STACKING": "1-8積み",
    "1-8 Stacking": "1-8積み",
    "Clear 40 LINES using 10 Quads in column 2 or 9": "2列目または9列目を開けてクアッド(テトリス)10回で40 LINESクリア",
    "Don't waste the I-Piece!": "Iミノを無駄にするな！",
    "MR. BOARDWIDE": "全列マスター",
    "Clear 40 LINES using a Quad in each of the 10 columns": "10個の全縦列それぞれでクアッドを決めて40 LINESクリア",
    "Master of all columns.": "全ての列を完璧に使いこなす者。",
    "10PC": "10PC",
    "Clear 40 LINES using only All Clears": "パフェ(All Clear)のみを10回続けて40 LINESクリア",
    "To clear without waste is to express the highest form of gratitude.": "無駄なく消し去ることこそ最高の敬意表現。",
    "BLITZER": "ブリッツァー",
    "points earned in completed BLITZ games": "BLITZ完走で獲得した累計スコア",
    "Two minutes of perfection.": "完璧に研ぎ澄まされた2分間。",
    "WABI-SABI": "侘寂 (ワビサビ)",
    "highest BLITZ score obtained without performing any All Clears": "パフェ(All Clear)を一度も使わずに獲得したBLITZハイスコア",
    "Two minutes of imperfection.": "不完全の中に宿る美しさ。",
    "AGAINST ALL ODDS": "下克上",
    "Against all Odds": "下克上",
    "games won against players with higher TR": "格上のTRを持つプレイヤーに勝利した回数",
    "Embrace the unexpected.": "波乱を楽しめ。",
    "CONTENDER": "挑戦者",
    "Contender": "挑戦者",
    "rounds played": "TETRA LEAGUEでプレイした総ラウンド数",
    '"Some day, everyone will remember your name!" -Tetra League Ad': '「いつか、誰もがあなたの名を知ることになる！」 - Tetra League 広告',
    "THE SPIKE OF ALL TIME": "伝説の火力（スパイク）",
    "The Spike of all Time": "伝説の火力（スパイク）",
    "largest spike sent (excluding margin time)": "一度におじゃまを送り出した最大火力（マージンタイム除く）",
    "Flashy techniques are a staple amongst Tetra League's glory-seeking competitors.": "栄光を追い求める者たちが放つ、ド派手な一撃。",
    "SPEED PLAYER": "スピードプレイヤー",
    "Speed Player": "スピードプレイヤー",
    "rounds won with a higher PPS than the opponent": "相手より高いPPSで勝利したラウンド数",
    "A simple strategy that can overwhelm even the most poised of masters.": "圧倒的な速度は、いかなる熟練者の冷静さも崩し去る。",
    "PLONK": "クロンク (戦術的低速)",
    "Plonk": "クロンク (戦術的低速)",
    "rounds won with a lower PPS than the opponent": "相手より低いPPSで勝利したラウンド数",
    "Pour intention into each piece, and even a single bag can shake the world.": "一目一目に魂を込めれば、速度に頼らずとも世界は揺らぐ。",
    "OPENER MAIN": "開幕特化",
    "rounds won within 20 seconds": "開始20秒以内に勝利したラウンド数",
    "A signature move worthy of being the first strike AND the calling card.": "名刺代わりの痛烈な先制攻撃。",
    "THE LOVERS": "恋人",
    "The Lovers": "恋人",
    'highest floor discovered with the "Duo" mod': '「Duo」MOD有効時に到達した最高階層',
    "Love, and resign yourself to the fate of another.": "愛とは、互いの運命を委ね合うこと。",
    "ZENITH EXPLORER": "ゼニス探検家",
    "Zenith Explorer": "ゼニス探探家",
    "highest floor discovered": "到達した最高階層",
    "Uncover the mysteries of the Zenith Tower.": "Zenith Towerの謎を解き明かせ。",
    "TOWER CLIMBER": "タワークライマー",
    "Tower Climber": "タワークライマー",
    "meters climbed": "登った総高度(メートル)",
    '"Have I been here before..?"': '「前にもここに来たことがあったような…？」',
    "WHATEVER IT TAKES": "どんな手段を使おうとも",
    "Whatever It Takes": "どんな手段を使おうとも",
    "players KO'd in Quick Play": "QUICK PLAYでKOしたプレイヤーの累計数",
    "Don't look back.": "振り向くな、前だけを見ろ。",
    "SUPERCHARGED": "フルチャージ",
    "Supercharged": "フルチャージ",
    "highest Back-to-Back chain reached in Quick Play": "QUICK PLAYで達成した最大B2B（バックトゥバック）数",
    '"With this divine power, we\'ll be unstoppable!" -Mathis, Core Engineer': '「この神聖なる力があれば、我々は無敵だ！」 - 主任エンジニア マティス',
    "TEMPERANCE": "節制",
    'highest floor discovered with the "No Hold" mod': '「ホールド禁止」MOD有効時に到達した最高階層',
    "Use each piece as they come and embrace the natural flow of stacking.": "与えられたミノをそのまま受け入れ、自然の流れるままに積め。",
    "VIP LIST": "VIPリスト",
    "End the week on weekly leaderboards with a high rank. (+10pts to Top 3, +5pts to Top 10, +3pts to Top 25, +1pts to Top 100)": "週間ランキングの上位で1週間を終える。(Top3: +10pt, Top10: +5pt, Top25: +3pt, Top100: +1pt)",
    "Unparalleled luxury for a select few.": "選ばれた一握りの者だけに与えられる極上の栄誉。",
    "THE EMPEROR": "皇帝",
    'highest floor discovered with the "Expert Mode" mod': '「エキスパートモード」MOD有効時に到達した最高階層',
    "A display of power for those willing to bear its burden.": "重圧を背負う覚悟を持つ者が見せる力の証明。",
    "THE DEVIL": "悪魔",
    'highest floor discovered with the "Double Hole Garbage" mod': '「ダブルホール」MOD有効時に到達した最高階層',
    "Redefine your limits or succumb to his chains.": "限界を超越するか、さもなくば悪魔の鎖に屈するか。",
    "STRENGTH": "力",
    'highest floor discovered with the "Volatile Garbage" mod': '「ボラティルおじゃま」MOD有効時に到達した最高階層',
    "Match great obstacles with greater determination.": "大いなる試練には、さらに強大な意志で立ち向かえ。",
    "THE TOWER": "塔",
    'highest floor discovered with the "Gravity" mod': '「重力」MOD有効時に到達した最高階層',
    "What will you do when it all comes crumbling down?": "すべてが崩れ去るとき、あなたはどう動く？",
    "WHEEL OF FORTUNE": "運命の輪",
    'highest floor discovered with the "Messier Garbage" mod': '「ばらばらおじゃま」MOD有効時に到達した最高階層',
    "The only constant in life is change.": "人生において唯一普遍なのは「変化」そのものだ。",
    "THE HERMIT": "隠者",
    'highest floor discovered with the "Invisible" mod': '「ステルス」MOD有効時に到達した最高階層',
    "When the outside world fails you, trust the voice within to light a path.": "視界が奪われたとき、己の内なる声を信じて道を照らせ。",
    "THE MAGICIAN": "魔術師",
    'highest floor discovered with the "All-Spin" mod': '「オールスピン」MOD有効時に到達した最高階層',
    "Inspiration is nothing short of magic.": "ひらめきとはまさに魔法そのもの。",
    "A MODERN CLASSIC": "モダンクラシック",
    'highest floor discovered while using the "No Hold" and "Gravity" mods': '「ホールド禁止」と「重力」MOD同時使用での最高到達階層',
    "Times were different back then...": "あの頃は、すべてが違っていた…",
    "DEADLOCK": "デッドロック",
    'highest floor discovered while using the "No Hold", "Double Hole Garbage" and "Messier Garbage" mods': '「ホールド禁止」「ダブルホール」「ばらばらおじゃま」同時使用での最高到達階層',
    '"Escape has become a distant dream, yet still we struggle..."': '「脱出は叶わぬ夢となっても、我々は抗い続ける…」',
    "THE ESCAPE ARTIST": "脱出手品師",
    'highest floor discovered while using the "Double Hole Garbage", "Messier Garbage" and "All-Spin" mods': '「ダブルホール」「ばらばらおじゃま」「オールスピン」同時使用での最高到達階層',
    '"An impossible situation! A daring illusionist! Will he make it out alive?"': '「絶対絶命の状況！大胆不敵な奇術師！果たして生きて出られるか！？」',
    "THE STARVING ARTIST": "苦境の芸術家",
    'highest floor discovered while using the "No Hold" and "All-Spin" mods': '「ホールド禁止」と「オールスピン」MOD同時使用での最高到達階層',
    "Creativity is cultivated through limitation.": "創造性とは制約の中でこそ洗練される。",
    "THE CON ARTIST": "ペテン師",
    'highest floor discovered while using the "Expert Mode", "Volatile Garbage" and "All-Spin" mods': '「エキスパート」「ボラティル」「オールスピン」同時使用での最高到達階層',
    "Would the perfect lie not be an art worthy of admiration?": "完璧な嘘もまた、称賛に値する芸術ではないだろうか？",
    "THE GRANDMASTER": "グランドマスター",
    'highest floor discovered while using the "Gravity" and "Invisible" mods': '「重力」と「ステルス」MOD同時使用での最高到達階層',
    'When the world descends into chaos, the grandmaster remains at peace.': '世界が混乱に陥ろうとも、グランドマスターの心は揺るがない。',
    "EMPEROR'S DECADENCE": "皇帝の墜落",
    'highest floor discovered while using the "Expert Mode", "Double Hole Garbage" and "No Hold" mods': '「エキスパート」「ダブルホール」「ホールド禁止」同時使用での最高到達階層',
    "The Devil's lesson in humility.": "悪魔が与えた謙虚さの教訓。",
    "DIVINE MASTERY": "神の領域",
    'highest floor discovered while using the "Expert Mode", "Double Hole Garbage", "Volatile Garbage" and "Messier Garbage" mods': '「エキスパート」「ダブルホール」「ボラティル」「ばらばらおじゃま」同時使用での最高到達階層',
    "The universe is yours.": "この全宇宙はあなたのものだ。",
    "SWAMP WATER": "泥沼の水",
    'highest floor discovered while using all mods other than "Duo" at the same time': '「Duo」以外の全MODを有効にして到達した最高階層',
    "The worst of all worlds.": "あらゆる悪夢を煮詰めた世界。",
    "TRAINED PROFESSIONALS": "熟練のプロフェッショナル",
    'highest floor discovered in a Duo while both players are using the "Expert Mode" mod': 'お互いに「エキスパート」MODを入れたDuoで到達した最高階層',
    "Partners in expertise.": "究極の技術で結ばれた相棒。",
    "THE RESPONSIBLE ONE": "救護班",
    "highest amount of revivals performed in a single Duo run": "1回のDuoプレイで味方を蘇生した最高回数",
    '"Could you please stop dying?"': '「頼むからもう死なないでくれ！」',
    "GUARDIAN ANGEL": "守護天使",
    "highest altitude to perform a successful revive at": "味方の蘇生に成功した最高高度",
    "An angel's intervention.": "舞い降りた天使の奇跡。",
    "EMPTY BOX": "空っぽの箱",
    "highest BLITZ score obtained without using Hold": "ホールドを一切使わずに獲得したBLITZハイスコア",
    "True minimalism is the art of letting go.": "真のミニマリズムとは手放す美学である。",
    "SWAMP WATER LITE": "ライト・スワンプウォーター",
    "highest floor discovered while using 7/8 of the difficulty mods (\"Duo\" not allowed)": "8つの難易度MODのうち7つを有効にして到達した最高階層（Duo除く）",
    "Comes in 8 different flavors!": "8つの異なる絶望フレーバーでお届け！",
    "BLOCK RATIONING": "ブロック配給制",
    "highest total attack within the first 400 pieces placed while using the \"Expert Mode\" and \"Messier Garbage\" mods": "「エキスパート」と「ばらばらおじゃま」MODで、最初の400ミノ以内に送った最大アタック数",
    "Adversity favors the resourceful.": "逆境は智恵ある者に味方する。",
    "TALENTLESS": "才能ゼロ",
    "highest floor discovered while using the \"All-Spin\" mod without performing any Spins": "「オールスピン」MODで一度もスピン消しをせずに到達した最高階層",
    "Reaching deep down but coming back empty every time.": "もがき続けながらも、何も得られず帰還する。",

    "LIVE NOW": "配信中",
    "TETRA NEWS": "TETRA ニュース",
    "clear 40 lines in the shortest amount of time possible.": "できるだけ早く40ラインを消去してください。",
    "score doesn't matter here, just go for the world record!": "スコアは無関係！世界記録を目指して走り抜けましょう！",
    "PERSONAL BEST": "自己ベスト",
    "RANDOM": "ランダム",
    "pick a completely random BGM for me": "完全にランダムでBGMを選曲",
    "RANDOM: CALM": "ランダム: 落ち着いた曲",
    "pick a random calmer BGM for me": "ゆったりとした曲調からランダム選曲",
    "RANDOM: BATTLE": "ランダム: 激しい曲",
    "pick a random intenser battle BGM for me": "アップテンポなバトル曲からランダム選曲",
    "CHIKA - INTERFACE": "CHIKA - INTERFACE",
    "KAMIYA - INTERFACE": "KAMIYA - INTERFACE",
    "TAKAYUKI - INTERFACE": "TAKAYUKI - INTERFACE",
    "KAMOKING - INTERFACE": "KAMOKING - INTERFACE",
    "MIRERA - INTERFACE": "MIRERA - INTERFACE",
    "KVK - CALM": "KVK - CALM",
    "CHIKA - CALM": "CHIKA - CALM",
    "TAKAHASHI TAKASHI - CALM": "高橋タカシ - CALM",
    "AKIKO SHIOYAMA - INTERFACE": "塩山由佳 - INTERFACE",
    "L-side - INTERFACE": "L-side - INTERFACE",
    "AIBA MAKOTO - CALM": "相場誠 - CALM",
    "CHIKA - SPECIAL": "CHIKA - SPECIAL",
    "FUJINAWA KAZUHIKO - INTERFACE": "藤縄和彦 - INTERFACE",
    "OMEGANE - INTERFACE": "OMEGANE - INTERFACE",
    "KAMOKING - CALM": "KAMOKING - CALM",
    "MEESAN - CALM": "MEESAN - CALM",
    "KAMOKING - BATTLE": "KAMOKING - BATTLE",
    "TOMOKI - BATTLE": "TOMOKI - BATTLE",
    "MIKIYA KOMABA - BATTLE": "駒場幹也 - BATTLE",
    "SUDO MIKADUKI - CALM": "SUDO MIKADUKI - CALM",
    "YOSHI - CALM": "YOSHI - CALM",
    "OMEGANE - CALM": "OMEGANE - CALM",
    "NOBUHAMU - CALM": "NOBUHAMU - CALM",
    "NAOKI HIRAI - CALM": "平井直樹 - CALM",
    "TSUTOMU - CALM": "TSUTOMU - CALM",
    "START": "スタート",
    "OPTIONS": "オプション",
    "pro mode": "プロモード",
    "alert on finesse fault": "フィネスミス時に警告表示",
    "retry on finesse fault": "フィネスミス時に即やり直し",
    "stride mode": "ストライドモード",
    "ADVANCED": "高度な設定",
    "press START to begin playing": "STARTを押してプレイを開始",
    "play as you wish! replays are not submitted.": "自由なルールでプレイ！リプレイは保存されません。",
    "EXPORT SETTINGS": "設定のエクスポート",
    "lvl": "Lv.",
    "CLOSE": "閉じる",
    "ago": "前",
    "GLOBAL": "世界",
    "COUNTRY": "国内",
    "Ǳ VIEW FULL PROFILE": "Ǳ プロフィールを表示",
    "SUPPORT TETR.IO": "TETR.IOを支援",
    "— osk, founder and developer of TETR.IO": "- osk, TETR.IO制作者・開発者",
    "...or pick a custom length (up to 1200 months)": "…または期間を直接指定 (最大1200ヶ月まで)",
    "CUSTOM LENGTH": "期間を指定",
    "enter an amount of months (max: 1200)": "月数を入力してください (最大: 1200)",
    "CANCEL": "キャンセル",
    "SUBMIT": "送信",
    "SUPPORT!": "サポーターになる！",
    "Gift to other player(s)": "他のプレイヤーにギフトを送る",
    "will be converted to your local currency on payment": "決済時に現地通貨へ自動換算されます",
    "fetching TETRA LEAGUE data…": "TETRA LEAGUE データを読み込み中…",
    "connecting to live servers…": "対戦サーバーへ接続中…",
    "RESET": "リセット",
    "OUT OF FOCUS": "フォーカスが外れています",
    "click to return to TETR.IO": "画面をクリックしてTETR.IOに戻る",
    "KEEP HOLDING TO RETRY": "長押しでリトライ",
    "KEEP HOLDING TO FORFEIT": "長押しでギブアップ",
    "RETRY": "リトライ",
    "BACK TO TITLE": "タイトルへ戻る",
    "CLEAR 40 LINES!": "40ライン消去せよ！",
    "replay will not be saved": "リプレイは保存されません",
    "USERNAME": "ユーザー名",
    "sfx": "効果音",
    "bgm": "BGM",
    "joining room…": "部屋に入室中…",
    "FRIEND": "フレンド",
    "BAD STANDING": "ペナルティ履歴あり",
    "one or more recent bans on record": "過去にBANや処罰を受けた履歴があります",
    "STARTING IN": "まもなく試合が開始されます…",
    "Super Lobby Mode Engaged - congratulations on hitting 100 players! Joins and leaves will be suppressed, and the winner of games in this room will earn a special profile badge!": "スーパーロビーモード有効化！参加者が100名に達しました！入退室メッセージが非表示になり、勝利者には特別なプロフィールバッジが授与されます！",
    "Super Lobby Mode Disengaged": "スーパーロビーモード解除",
    "message...": "メッセージを入力…",
    "PLAYING": "対戦中",
    "click to switch to SPECTATORS": "クリックで観戦者に切替",
    "ROYALE KNOCKOUT": "ロイヤル KO",
    "PM": "午後",
    "requesting account data…": "アカウントデータを要求中…",
    "ACCOUNT": "アカウント",
    "change account settings": "アカウント設定を変更",
    "hover over a setting for more info": "設定項目にマウスを合わせると説明が表示されます",
    "CONTROLS": "操作設定",
    "HANDLING": "操作感度 (DAS/ARR)",
    "VOLUME & AUDIO": "音量・サウンド",
    "GAMEPLAY": "ゲームプレイ",
    "VIDEO & INTERFACE": "画面・画面表示",
    "CUSTOMIZATION": "カスタマイズ",
    "VERSUS KNOCKOUT": "VS KO",
    "HOST": "ホスト (部屋主)",
    "Welcome to chat! Please remember to be civil to your opponents.": "チャットへようこそ！相手に敬意を持って会話しましょう。",
    "SAVE": "保存",
    "click to copy url": "クリックしてURLをコピー",
    "this user is playing anonymously": "このユーザーは匿名でプレイしています",
    "WELCOME": "ようこそ",
    "ROOM": "ルーム",
    "MATCH": "マッチ",
    "GAME": "ゲーム",
    "loading SFX...": "効果音を読み込み中…",
    "checking for game updates...": "アップデートを確認中…",
    "loading home banner data...": "バナーデータを読み込み中…",
    "initializing benchmark...": "ベンチマークを初期化中…",
    "running benchmark...": "ベンチマークを実行中…",
    "GENERAL": "一般",
    "OBJECTIVE": "目標",
    "relax or train in a neverending mode! your progress is stored across games.": "エンドレスモードでリラックスや練習をしよう！進行状況は保存されます。",
    "adjust the feel or help train using the ZEN SIDEBAR.": "ZENサイドバーを使って、スピードやゲーム環境を調整できます。",
    "you can undo and redo placements with CTRL+Z and CTRL+Y!": "Ctrl+Z で一手戻す、Ctrl+Y でやり直すことができます！",
    "H": "時間",
    "THE TEAM": "制作チーム",
    "FOUNDER & LEAD PRODUCER": "創設者 & 開発リーダー",
    "programming, graphics design, production, general development": "プログラミング、グラフィックデザイン、制作全般",
    "your currently set keybinds are:": "現在のキー割り当て設定:",
    "[NOT SET]": "[未設定]",
    "press any key or button": "割り当てたいキーやボタンを押してください",
    "click anywhere to remove the keybind": "画面をクリックするとキー割り当てを解除します",
    "move falling piece left": "ミノを左に移動",
    "move falling piece right": "ミノを右に移動",
    "soft drop": "ソフトドロップ",
    "hard drop": "ハードドロップ",
    "rotate counterclockwise": "反時計回りに回転 (左回転)",
    "rotate clockwise": "時計回りに回転 (右回転)",
    "rotate 180": "180度回転",
    "swap hold piece": "ホールド",
    "you can change these and many other settings in CONFIG.": "設定画面 (CONFIG) でこれらのキーや各種項目を変更できます。",
    "click on the tabs above to explore and/or change room options as you wish. have fun!": "上のタブをクリックしてルールを自由にカスタマイズしましょう。楽しんで！",
    "GOT IT!": "了解！",
    "room name": "部屋の名前",
    "room configuration updated!": "ルーム設定が更新されました！",
    "room configuration updated partially": "ルーム設定の一部が更新されました",
    "presets must be ASCII characters. sorry!": "プリセット名は半角英数字で入力してください！",
    "room name must be ASCII characters. sorry!": "部屋名は半角英数字で入力してください！",
    "unknown match gamemode": "不明な試合モード",
    "unknown bag type": "不明なバッグ形式",
    "unknown spin bonus type": "不明なスピンボーナス形式",
    "unknown combo table": "不明なコンボ倍率表",
    "unknwon target bouns type": "不明なターゲットボーナス形式",
    "unknwon garbage entry type": "不明なおじゃま競合形式",
    "unknown garbage rule": "不明なおじゃマルール",
    "unknown passthrough mode": "不明な貫通モード",
    "player limit": "最大プレイヤー数",
    "auto start": "自動スタート",
    "public room": "公開ルーム",
    "allow anonymous users to join": "匿名ユーザーの参加を許可",
    "allow users who are in matchmaking to join": "マッチメイキング中のユーザーの参加を許可",
    "allow unranked users to play": "アンランクユーザーの参加を許可",
    "rank limit": "ランク制限",
    "limit by top rank": "最高ランクで制限",
    "music": "BGM",
    "gamemode": "ゲームモード",
    "VERSUS": "対戦 (VERSUS)",
    "[2 - ∞ players] great for 1v1 and small lobbies!": "[2〜∞人] 1v1や小規模ロビーに最適な対戦モード！",
    "BATTLE ROYALE": "バトルロイヤル",
    "[2 - ∞ players] a full-fledged battle royale gamemode great for big lobbies!": "[2〜∞人] 大規模ロビー向けの本格バトルロイヤル！",
    "PRACTICE": "プラクティス",
    "[2 players] great for live training with a friend! enables undoing and resetting your board": "[2人専用] フレンドとのリアルタイム練習に最適！盤面リセットや巻き戻しが可能です",
    "first to (FT)": "先勝数 (FT)",
    "win by (WB)": "勝ち越し差 (WB)",
    "stock": "ストック (残機)",
    "link copied!": "リンクをコピーしました！",
    "replay link copied!": "リプレイリンクをコピーしました！",
    "EDIT": "編集",
    "THIS ACTION REQUIRES SUPPORTER": "この機能にはサポーター権限が必要です",
    "game presets": "ゲームプリセット",
    "random bag type": "RANDOM BAGタイプ",
    "allowed spins": "スピン判定の許可",
    "T-SPINS": "T-スピンのみ",
    "receive bonuses for spinning T-pieces": "Tミノのスピン消しのみボーナスが発生します。",
    "ALL-SPIN": "オールスピン",
    "ALL-SPINS": "オールスピン",
    "receive bonuses for spinning all pieces": "すべてのミノのスピン消しでボーナスが発生します。",
    "HANDHELD": "オールスピン (攻撃軽減)",
    "receive bonuses for spinning all pieces BUT attacks are halved except for T-SPINS": "全ミノでスピンボーナスが出ますが、Tスピン以外の攻撃力は半減します。",
    "recieve bonuses for spinning all pieces. non T-SPINS attacks are halved. pieces use 4-corner detection": "全ミノでスピン判定を有効化。Tスピン以外のアタック力は半減され、4コーナー判定を使用します。",
    "STUPID": "何でもスピン (Oスピン対応)",
    "everything is a spin because YEAH WHY NOT (O-spin SUPPORTED!)": "すべてのミノがスピン扱いになります (Oスピンも判定されます！)",
    "receive no spin bonuses": "スピンボーナスを無効化します",
    "combo table": "コンボ倍率表",
    "NONE": "なし",
    "ALL-MINI": "オールミニ",
    "receive bonuses for spinning T-pieces and receive back-to-back for spinning all other pieces": "Tスピンにボーナスが付与され、他のミノのスピン消しはB2Bを維持します。",
    "disable combo chaining": "コンボ補正を無効化",
    "MULTIPLIER": "コンボ倍率方式",
    "TETR.IO's combo multiplier": "TETR.IO独自のコンボ倍率",
    "CLASSIC GUIDELINE": "クラシック・ガイドライン",
    "classic guideline combo table": "標準的なガイドライン基準のコンボ倍率表",
    "MODERN GUIDELINE": "モダン・ガイドライン",
    "modern guideline combo table": "現代的なガイドライン基準のコンボ倍率表",
    "allow 180 spins": "180度回転を許可",
    "kick table": "キックテーブル",
    "bombs-style garbage": "ボム風おじゃま",
    "use hard drop": "ハードドロップを使用",
    "use NEXT queue": "NEXT表示を使用",
    "use HOLD queue": "HOLD機能を使用",
    "next pieces": "NEXT表示数",
    "infinite movement": "無限設置 (インフィニティ)",
    "show shadow piece": "ゴースト（影）を表示",
    "line clear ARE": "ライン消去ARE (硬直時間)",
    "enforce below handling settings": "以下の操作感度設定を強制適用",
    "GRAVITY & LEVELLING": "重力 & レベル",
    'use levelling (overrides "gravity")': 'レベル上昇を使用 ("重力"設定を上書き)',
    "enforced ARR": "ARR強制指定",
    "enforced DAS": "DAS強制指定",
    "enforced SDF": "SDF強制指定",
    "disable knockout": "KO（ドボン）を無効化",
    "board width": "盤面の横幅",
    "board height": "盤面の高さ",
    "GRAVITY & MARGIN TIME": "重力 & マージンタイム",
    "gravity": "重力 (落下速度)",
    "SUBZERO": "超低速",
    "RELAXED": "低速",
    "ENGAGING": "標準",
    "SPICY": "高速",
    "STATIC": "固定",
    "static gravity": "重力を固定",
    "speed": "スピード",
    "efficiency": "効率",
    "BACKFIRE 0.5X": "バックファイア 0.5X",
    "BACKFIRE 1X": "バックファイア 1X",
    "BACKFIRE 2X": "バックファイア 2X",
    "UNCLEAR 0.5X": "アンクリア 0.5X",
    "UNCLEAR 1X": "アンクリア 1X",
    "UNCLEAR 2X": "アンクリア 2X",
    "CHEESE LAYER": "チーズレイヤー",
    "CHEESE TIMER": "チーズタイマー",
    "cheese messiness %": "チーズおじゃまの乱れ度 %",
    "gravity increase": "重力増加量",
    "gravity margin time": "重力マージンタイム",
    "garbage multiplier": "おじゃま倍率",
    "garbage margin time": "おじゃまマージンタイム",
    "garbage increase": "おじゃま増加量",
    "messiness on change": "変化時のおじゃまの乱れ度",
    "messiness within attack": "1攻撃内のおじゃまの乱れ度",
    "avoid same column RNG": "同じ列への連続穴生成を回避",
    "messiness timeout": "乱れ度リセット判定時間",
    "garbage cap increase": "おじゃま上限の増加量",
    "garbage cap max": "おじゃまの最大相殺上限",
    "garbage absolute cap": "おじゃまの絶対受入上限",
    "garbage phase": "おじゃまフェーズ",
    "garbage target bonus": "ターゲットボーナス",
    "no bonus whatsoever": "ボーナスなし",
    "DEFENSIVE": "防御的",
    "a bonus is added when defending incoming attacks": "受けている攻撃を防御（相殺）した際にボーナスが付与されます",
    "OFFENSIVE": "攻撃的",
    "a bonus is added to both defense and offence": "攻撃時と防御時の両方にボーナスが付与されます",
    "garbage entry": "おじゃまの上昇方式",
    "INSTANT": "即時発生",
    "garbage enters instantly": "おじゃまラインが即座にせり上がります",
    "CONTINUOUS": "連続発生",
    "garbage rolls in one by one": "おじゃまラインが1列ずつ滑らかに上がります",
    "DELAYED PIECE SPAWN": "ミノ出現遅延",
    "garbage rolls in one by one but delays your next piece": "おじゃまが1列ずつ上がると同時に、次のミノ出現が少し遅れます",
    "opener phase": "開幕フェーズ",
    "garbage are": "おじゃま発生ARE",
    "garbage queue": "おじゃまゲージ (保留欄)",
    "garbage blocking": "おじゃま相殺/キャンセル",
    "COMBO BLOCKING": "コンボキャンセル",
    "incoming garbage will be delayed and reduced on successive line clears": "連続してラインを消している間、おじゃまの上昇が遅延・減少します",
    "LIMITED BLOCKING": "制限キャンセル",
    "incoming garbage can be reduced only once per next immediate piece": "次のミノ1個につき、1回だけおじゃまを相殺できます",
    "incoming garbage cannot be blocked": "おじゃまの相殺・防御を禁止します",
    "garbage passthrough": "おじゃまの相殺打ち消し",
    "ZERO": "完全相殺",
    "opposing attacks in transit always cancel eachother out": "飛んでいる最中の相手の攻撃を常に相殺し合います",
    "LIMITED": "限定相殺",
    "opposing attacks in transit cancel out while garbage is flying": "おじゃまが飛んでいる間のみ相殺が有効になります",
    "CONSISTENT": "持続相殺",
    "opposing attacks in transit cancel out except when garbage is flying": "おじゃまが着弾しようとしている瞬間を除き相殺します",
    "opposing attacks in transit do not cancel eachother out": "飛んでいる最中の相殺を行いません",
    "allow manual targeting": "手動ターゲット切替を許可",
    "enable back-to-back chaining": "B2B（バックトゥバック）チェーンを有効化",
    "enable back-to-back charging": "B2B（バックトゥバック）チャージを有効化",
    "enable all clears": "オールクリア(パフェ)を有効化",
    "all clear garbage": "パフェ時のおじゃま送信量",
    "all clear back-to-back": "パフェ時のB2B加算",
    'use random seed (overrides "seed")': 'ランダムシードを使用 ("シード"指定を上書き)',
    "rounding mode": "端数処理モード",
    "DOWN": "切り捨て",
    "all values are rounded down": "すべての端数値を切り捨てます",
    "weighted randomness is used to smooth values (e.g. 1.23 has a 23% chance to become 2)": "確率的な加重ランダムを用いて端数を滑らかにします（例: 1.23は23%の確率で2になります）",
    "use master levels": "マスターレベルを使用",
    "starting level": "開始レベル",
    "level speed": "レベルの上昇速度",
    'use static levelling (overrides "level speed")': '固定レベルを使用 ("上昇速度"を上書き)',
    "level static speed": "レベル固定スピード",
    "base gravity": "基本落下速度",
    "lock delay": "ロックダウン猶予 (固定時間)",
    "seed": "シード値",
    "allow retry": "やり直し (リトライ) を許可",
    "enable clutch clears": "クラッチクリアを有効化",
    "disable lockout": "画面外溢れ敗北(ロックアウト)を無効化",
    "SURVIVAL": "サバイバル",
    "mode": "モード",
    "do not spawn any garbage": "おじゃまを生成しない",
    "LAYER": "レイヤー",
    "keep a layer of garbage on the board": "常に一定のおじゃま層を維持",
    "TIMER": "タイマー",
    "spawn garbage on a timer": "タイマー経過に応じておじゃまを生成",
    "garbage messiness %": "おじゃまの乱れ度 %",
    "garbage travel speed": "おじゃまのせり上がり速度",
    "garbage cap": "おじゃまの同時せり上がり上限",
    "layer height": "維持するレイヤーの高さ",
    "sticky layer": "粘着レイヤー",
    "minimum layer height": "最小レイヤー高度",
    "timer interval": "タイマー間隔",
    "key": "判定キー",
    "final score will be displayed": "最終スコアを表示します",
    "final time will be displayed": "最終タイムを表示します",
    "final line count will be displayed": "最終消去ライン数を表示します",
    "objective": "クリア目標",
    "play infinitely": "エンドレスでプレイ",
    "get to a set amount of lines to clear": "指定のライン数を消すとクリア",
    "TIMED": "時間制限",
    "timed": "時間制限",
    "play for a set amount of time to clear": "指定時間生き残るとクリア",
    "get to a set amount of garbage lines to clear": "指定のおじゃまライン数を消化するとクリア",
    "count": "数値",
    "FINAL LINE COUNT": "最終ライン数",
    "topping out is OK": "窒息(トップアウト)してもクリア扱い",
    "display objective behind board": "盤面背景に目標を表示",
    "META": "メタ設定",
    "INTRO": "カウントダウン",
    "mission": "ミッション",
    "play countdown": "カウントダウンを行う",
    "countdown count": "カウントダウン回数",
    "countdown interval": "カウントダウン間隔",
    "time before countdown": "カウントダウン開始前の時間",
    "time before start": "スタート前の時間",
    "zoom animation": "ズーム演出",
    "NO ANIMATION": "アニメーションなし",
    "display no animation": "アニメーションを表示しない",
    "display a fast animation": "速いアニメーションを表示",
    "display a slow animation": "ゆっくりしたアニメーションを表示",
    "CINEMATIC": "シネマティック",
    "display a very slow animation": "重厚で非常にゆっくりしたアニメーションを表示",
    "COUNTERS": "カウンター表示",
    "left counter slot 1": "左側カウンター 枠1",
    "left counter slot 2": "左側カウンター 枠2",
    "left counter slot 3": "左側カウンター 枠3",
    "left counter slot 4": "左側カウンター 枠4",
    "right counter slot": "右側カウンター 枠",
    "use the default option": "デフォルトを使用",
    "EMPTY": "なし",
    "---empty---": "---なし---",
    "---default---": "---デフォルト---",
    "leave this slot empty": "このスロットを空欄にする",
    "display the score in this slot": "このスロットにスコアを表示",
    "SCORE (per piece)": "スコア (ミノ毎)",
    "親切": "詳細スコア",
    "display the score and score per piece in this slot": "スコアとミノあたりの獲得スコアを表示",
    "STOPWATCH": "ストップウォッチ",
    "display the time passed in this slot": "経過時間を表示",
    "display the time remaining in this slot (for TIMED objective)": "残り時間を表示 (時間制限目標時)",
    "display the amount of cleared lines in this slot": "消去したライン数を表示",
    "display the current level in this slot": "現在のレベルを表示",
    "PIECES": "ミノ数",
    "display the amount of placed pieces and speed in this slot": "設置したミノ数と速度(PPS)を表示",
    "INPUTS": "打鍵数 (キー入力)",
    "display the amount of buttonpresses in this slot": "押されたキーの回数を表示",
    "FINESSE": "フィネス (最適操作)",
    "display your finesse in this slot": "フィネス精度を表示",
    "FINESSE (SMALLER)": "フィネス (小型)",
    "display your finesse in this slot (for use on the left-hand side)": "フィネスを表示 (左側表示に最適化)",
    "HOLD": "ホールド",
    "display the amount of held pieces in this slot": "ホールドを行った回数を表示",
    "display the amount of ALL CLEARS in this slot": "オールクリア(パフェ)達成回数を表示",
    "GARBAGE CLEARED": "消去したおじゃま",
    "display the amount of garbage lines cleared in this slot": "消化したおじゃまライン数を表示",
    "enforce absolute line count": "絶対ライン数を強制",
    "display progress bar": "進捗ゲージを表示",
    "GAME OVER": "ゲームオーバー",
    "END RESULT": "最終結果",
    "global rank": "世界順位",
    "GLOBAL RANK": "世界順位",
    "personal rank": "個人順位",
    "PERSONAL RANK": "個人順位",
    "PERSONAL BEST!": "自己ベスト更新！",
    "PERSONAL BEST": "自己ベスト",
    "WORLD RECORD!": "世界新記録！",
    "spins": "スピン",
    "spin minis": "スピン ミニ",
    "spin mini singles": "スピン ミニシングル",
    "spin singles": "スピン シングル",
    "spin mini doubles": "スピン ミニダブル",
    "spin doubles": "スピン ダブル",
    "spin triples": "スピン トリプル",
    "spin quads": "スピン クアッド",
    "AGAIN": "もう一度",
    "GLOBAL MODERATION & COMMUNITY MANAGEMENT TEAM": "グローバルモデレーション & コミュニティ管理チーム",
    "MUSIC BY": "楽曲制作",
    "DEFAULT WALLPAPERS PROVIDED BY": "デフォルト壁紙提供",
    "THIRD-PARTY TECHNOLOGIES (": "使用サードパーティ技術 (",
    "SPECIAL THANKS": "スペシャルサンクス",
    "THANK YOU FOR PLAYING.": "プレイしていただきありがとうございます。",
    "TETR.IO, THE TETR.IO LOGO, TETRA LEAGUE, OSK, AND THE OSK LOGO ARE TRADEMARKS OF OSK.": "TETR.IO、TETR.IOのロゴ、TETRA LEAGUE、OSK、およびOSKのロゴはOSKの商標です。",
    "ALL OTHER TRADEMARKS ARE THE PROPERTY OF THEIR RESPECTIVE OWNERS, TRADEMARK FAIR USE DOCTRINES APPLY.": "その他すべての商標はそれぞれの所有者に帰属します。",
    "VIEW ALL": "すべて表示",
    "GLOBAL MODERATOR": "グローバルモデレーター",
    "ADMINISTRATOR": "管理者",
    "community moderator": "コミュニティモデレーター",
    "assisting global moderator": "アシスタントグローバルモデレーター",
    "PROGRAMMING": "プログラミング",
    "AUDIO, MUSIC, PROGRAMMING": "オーディオ、音楽、プログラミング",
    "assisting PROGRAMMING": "プログラミング補佐",
    "GAME DESIGN": "ゲームデザイン",
    "assisting GRAPHICS DESIGN": "グラフィックデザイン補佐",
    "forfeit game": "ギブアップ",
    "retry game": "やり直し (リトライ)",
    "open chat": "チャットを開く",
    "pick targeting strategy": "ターゲット戦略を変更",
    "move in menus": "メニュー移動",
    "confirm in menus": "決定",
    "open social overlay": "ソーシャル画面を開く",
    "back in menus": "戻る",
    "controllers can be set up in CUSTOM controls - just press the controller buttons you wish to bind.": "コントローラーの設定はカスタムコントロールで行えます。割り当てたいボタンを押してください。",
    "controller sensitivity": "コントローラー感度",
    "vibration intensity": "振動の強さ",
    "GUIDELINE": "ガイドライン",
    "LOW": "低",
    "HIGH": "高",
    "WEAK": "弱",
    "STRONG": "強",
    "SLOW": "遅い",
    "FAST": "速い",
    "prevent accidental hard drops": "誤操作によるハードドロップを防止 (HD猶予)",
    "cancel DAS when changing directions": "方向変更時にDASをリセット",
    "prefer soft drop over movement": "横移動よりソフトドロップを優先",
    "MUSIC": "BGM音量",
    "QUIET": "小",
    "LOUD": "大",
    "SFX": "効果音量",
    "stereo": "ステレオ感",
    "NO STEREO": "モノラル (ステレオなし)",
    "SUPER STEREO": "強力なステレオ効果",
    "MUTE": "ミュート",
    "scroll to change volume": "スクロールで音量を調整",
    "mute music when hidden": "ウィンドウ非アクティブ時にBGMを消す",
    "hear next pieces": "NEXT出現音を鳴らす",
    "hear other players": "他のプレイヤーの操作音を鳴らす",
    "hear attacks": "攻撃音を鳴らす",
    "do not reset music when retrying": "リトライ時にBGMを最初からかけ直さない",
    "disable sound entirely": "すべてのサウンドを完全に無効化",
    "TEST": "テスト再生",
    "TWEAK MUSIC": "BGMの個別調整",
    "ACTION TEXT": "アクションテキスト (技名表示)",
    "ON": "オン",
    "OFF": "オフ",
    "SOME": "一部のみ",
    "board bounciness": "盤面のバウンド揺れ",
    "STIFF": "揺らさない",
    "BOUNCY": "大きく揺らす",
    "damage shakiness": "ダメージ時の画面の揺れ",
    "SHAKY": "激しく揺らす",
    "grid visibility": "マス目の濃さ (グリッド)",
    "TRANSPARENT": "透明",
    "OPAQUE": "くっきり",
    "spectating": "観戦中",
    "board visibility": "盤面の濃さ",
    "shadow visibility": "ゴースト（影）の濃さ",
    "board zoom": "盤面のズーム（大きさ）",
    "FAR": "遠く",
    "NEAR": "近く",
    "show duels side-by-side": "1v1対戦時に盤面を左右に並べて表示",
    "spin board when you T-spin": "Tスピン時に盤面を回転させる",
    "alert me when i KO someone": "相手をKOした時に通知を表示",
    "enable the fire meter": "ファイヤーメーター（連勝演出）を有効化",
    "warn me when i'm in danger": "ピンチ時に危険警告エフェクトを表示",
    "colored shadow piece": "ゴースト（影）をミノの色と同色にする",
    "gray out locked HOLD piece": "ロックされたホールドミノをグレーアウト表示",
    "GRAPHICS": "グラフィック画質",
    "MINIMAL": "最低",
    "MEDIUM": "中",
    "ULTRA": "最高",
    "CACHING": "キャッシュ方式",
    "BALANCED": "バランス",
    "AGGRESSIVE": "高速化重視",
    "WEBGL MODE": "WebGL モード",
    "LEGACY": "レガシー",
    "particle count": "パーティクル（火花）の量",
    "FEW": "少ない",
    "LOTS": "多い",
    "background visibility": "背景画像の濃さ",
    "bloom filter power": "発光 (ブルーム) エフェクトの強さ",
    "chromatic aberration": "色収差エフェクト",
    "flashwave power": "フラッシュウェーブ（波紋）の強さ",
    "you just created an online game - you can start the game once two players are in the room (and not spectating)!": "対戦部屋を作成しました！観戦者以外のプレイヤーが2人以上揃ったらゲームを開始できます！",
    "you just joined an online game - the game will start whenever the HOST presses START. good luck!": "部屋に参加しました！ホストがSTARTを押すとゲームが始まります。健闘を祈ります！",
    "you just joined an online game - the HOST can start the game once two players are in the room (and not spectating)!": "部屋に参加しました！観戦者以外のプレイヤーが2人揃うとホストがゲームを開始できます！",
    "you just created an online game - the game will start whenever you press START. good luck!": "対戦部屋を作成しました！STARTを押すといつでもゲームを開始できます。健闘を祈ります！",
    "render at a low resolution": "低解像度でレンダリングする",
    "less precision on counters": "カウンターの更新頻度を落として軽量化",
    "always simplify multiplayer thumbnails": "マルチプレイ時の他人の盤面サムネイルを簡易表示化",
    "do not animate background in super lobbies": "スーパーロビーで背景アニメーションを停止",
    "do not animate background in quick play": "QUICK PLAYで背景アニメーションを停止",
    "no background in menus": "メニュー画面の背景アニメーションをOFFにする",
    "filter profanity in chat": "チャットで不適切な言語・暴言をフィルター",
    "hide chat when ingame": "ゲームプレイ中はチャットを非表示にする",
    "hide room IDs": "画面上のルームIDを隠す (配信者向け)",
    "show emotes in chat": "チャットで絵文字を表示する",
    "show animated emotes in chat": "チャットでアニメーション絵文字を表示する",
    "invert chat colors": "チャットの文字色を反転する",
    "darken screen behind chat": "チャット背景を暗くして読みやすくする",
    "keep replay tools open": "リプレイ操作ツールを常に開いた状態にする",
    "hide network warning icons": "回線警告アイコンを非表示にする",
    "warn me when the game is not focused": "画面のフォーカスが外れている時に警告する",
    "show the welcome guide": "ウェルカムガイドを表示する",
    "use custom background image": "カスタム背景画像を使用する",
    "background URL (use multiple by separating with commas, confirm with ENTER)": "壁紙画像URL (カンマ区切りで複数指定可能。Enterで確定)",
    "show desktop notifications": "デスクトップ通知を表示",
    "suppress notifications while ingame": "ゲームプレイ中は通知を一時停止",
    "always play notification sounds at full volume": "通知音を常に最大音量で再生",
    "NOTIFY ME WHEN A FRIEND GOES ONLINE": "フレンドがオンラインになった時に通知",
    "NOTIFY ME WHEN A FRIEND GOES OFFLINE": "フレンドがオフラインになった時に通知",
    "NOTIFY ME WHEN A FRIEND SENDS ME A DIRECT MESSAGE": "フレンドからDMが届いた時に通知",
    "NOTIFY ME WHEN A NON-FRIEND SENDS ME A DIRECT MESSAGE": "フレンド以外からDMが届いた時に通知",
    "NOTIFY ME WHEN SOMEONE INVITES ME TO A ROOM": "ルームへの招待を受け取った時に通知",
    "OTHER NOTIFICATIONS": "その他の通知",
    "INGAME": "ゲーム内のみ",
    "INGAME & DESKTOP": "ゲーム内 & デスクトップ",
    "targeting strategy even": "ターゲット方式: 均等 (EVEN)",
    "targeting strategy eliminations": "ターゲット方式: とどめ (ELIMS)",
    "targeting strategy random": "ターゲット方式: ランダム (RANDOM)",
    "targeting strategy payback": "ターゲット方式: 反撃 (PAYBACK)",
    "menus: up": "メニュー: 上移動",
    "menus: down": "メニュー: 下移動",
    "menus: left": "メニュー: 左移動",
    "menus: right": "メニュー: 右移動",
    "menus: confirm": "メニュー: 決定",
    "menus: back": "メニュー: 戻る",
    "GO!": "GO!",
    "even": "均等",
    "elims": "とどめ",
    "random": "無差別",
    "payback": "反撃",
    "started the game": "がゲームを開始しました",
    "you ko'd yourself": "自爆（自責KO）",
    "POINTS": "ポイント",
    "LINES RECEIVED": "受け取ったおじゃま",
    "LINES SENT": "送ったおじゃま",
    "RESULTS": "リザルト",
    "game submitted!": "スコアデータ送信完了！",
    "NEXT": "次へ",
    "the results are in!": "勝敗が決しました！",
    "kick": "キック (一時追放)",
    "ban": "BAN (部屋からの追放)",
    "move to players": "対戦枠へ移動",
    "move to spectators": "観戦枠へ移動",
    "transfer ownership": "部屋主(ホスト)権限を譲渡",
    "joining room": "入室中",
    "you are now host of this room!": "あなたがこのルームの部屋主(ホスト)になりました！",
    "you were moved to spectators for being AFK": "放置（AFK）のため観戦者枠へ移動されました",
    "SURVIVOR": "生存者",
    "ANONYMOUS": "匿名",
    "SPECTATING": "観戦中",
    "click to switch to PLAYERS": "クリックで対戦プレイヤー枠へ移動",
    "[SYS]": "[システム]",
    "game finished": "ゲーム終了",
    "was kicked from the room": "が部屋からキックされました",
    "was banned from the room": "が部屋からBANされました",
    "KICKED BY ROOM OWNER": "部屋主によりキックされました",
    "you were kicked from the room by its owner.": "部屋主の手によって部屋から追放されました。",
    "BANNED BY ROOM OWNER": "部屋主によりBANされました",
    "you were banned from the room by its owner.": "部屋主の手によってこの部屋への参加を禁止されました。",
    "you are banned from this room. please try again later, or ask the host to unban you with /unban": "この部屋からBANされています。時間をおくか、ホストに /unban を依頼してください。",
    "[CMD]": "[コマンド]",
    "WINNER!": "勝利！",
    "GAME!": "決着！",
    "leaving room...": "部屋を退出中…",
    "Ǿ SAVE REPLAY": "Ǿ リプレイを保存",
    "ALIVE": "生存時間",
    "you can change these and many other settings in CONFIG. have fun!": "各種設定はCONFIGから変更可能です。ゲームをお楽しみください！",
    "hover for more info!": "マウスを重ねると詳しい情報を表示します！",
    "you just joined QUICK PLAY - you will play in the next game in this lobby. please wait for the current game to finish. feel free to spectate or play ZEN while waiting!": "QUICK PLAYに参加しました！次のゲームから参加となります。現在の試合が終わるまで観戦やZENモードでお待ちください！",
    "you just joined QUICK PLAY - the next game will start automatically. please wait just a moment longer!": "QUICK PLAYに参加しました！間もなく次の試合が自動で開始されます。少々お待ちください！",
    "OK": "OK",
    "disconnected from server": "サーバーとの接続が切断されました",
    "CONNECTION ERROR": "接続エラー",
    "the server has disconnected you.": "サーバーによって切断されました。",
    "please check your internet connection and configuration.": "通信環境やネットワーク設定を確認してください。",
    "due to browser limitations, tabbing out of TETR.IO midgame may cause disconnects.": "ブラウザの仕様により、対戦中に別タブに切り替えると切断される場合があります。",
    "opponent forfeited": "対戦相手が棄権しました",
    "no such room": "指定の部屋が存在しません",
    "ANONYMOUS USERS CANNOT EDIT THEIR ACCOUNTS": "匿名ユーザーはアカウント設定を変更できません",
    "the username ": "ユーザー名「",
    " is registered. please enter your password to log in": "」はすでに登録されています。ログインするにはパスワードを入力してください",
    "MISC": "その他",
    "LEVELING": "レベルシステム",
    "DISCREET": "目立たない表示",
    "INFINITE HOLD": "無限ホールド",
    "SPINS": "スピンルール",
    "COMBO TABLE": "コンボ補正表",
    "KICK TABLE": "キックテーブル",
    "GRAVITY": "重力 (落下度)",
    "DISPLAY": "画面表示",
    "GARBAGE": "おじゃまライン",
    "DEFAULT": "デフォルト",
    "TETR.IO's premier room settings. optimized for battles with small groups or duels against friends and foes alike!": "TETR.IO標準のルーム設定。少人数対戦やフレンドとのガチンコ勝負に最適化されています！",
    "settings copied directly from TETR.IO's matchmaking rooms! margin times and match goals are shifted slightly with duels in mind.": "TETRA LEAGUEの公式対戦ルールをベースにした設定です！1v1向けにマージンタイム等が調整されています。",

    "TETRA LEAGUE (season 1)": "TETRA LEAGUE (シーズン1)",
    "last season's TETRA LEAGUE rules!": "前シーズンのTETRA LEAGUE公式ルール！",
    "ENFORCED DELAYS": "遅延・入力固定",
    "this preset introduces several forms of enforced handling which introduces a generous skill ceiling! puts a focus on efficient and consistent play, as opposed to deafeningly fast rounds.": "操作感度に一律の制限をかけ、超高速操作よりも正確で効率的な配置テクニックを重視させるルールです。",
    "4-WIDE": "4-WIDE (4ワイド練習)",
    "this party-focused preset uses a nonstandard board size which allows you to infinitely combo.": "特殊な横幅で無限にコンボを繋げることができるパーティ向けルールです。",
    "100 BATTLE ROYALE": "100人 バトルロイヤル",
    "this preset is similar to the BATTLE ROYALE gamemode but at a slower pace.": "バトルロイヤルモードを少しゆったりしたペースで遊べる設定です。",
    "CLASSIC": "クラシック (レトロ系)",
    "an endurance-focused challenge of pure stacking intellect! almost every value is changed to imitate stacker games made many years ago.": "古き良きレトロパズルゲームを再現。不自由な操作感の中で純粋な平積み・積載技術が試されます。",
    "ARCADE": "アーケード",
    "featuring innovative mechanics created for a popular stacker found in arcades, this preset puts a focus on smart stacking and mastery with its custom kick table!": "アーケードで人気を博した名作ゲームの挙動を模した、独自のキックテーブルを持つ技術系ルールです。",
    "BOMBS": "ボム対戦",
    "versus with an explosive twist! stack pieces on top of garbage to clear it and send devastating attacks to your opponents!": "おじゃまブロックの上にミノを設置して爆破消去！大火力を相手に送り込む爆発対戦モード！",
    "LEGACY QUICK PLAY": "旧 QUICK PLAY",
    "this legacy preset emulates TETR.IO's QUICK PLAY experience pre 6.4.0": "Ver 6.4.0以前の旧QUICK PLAY仕様を再現したルールです",
    "7-BAG": "7-BAG (7種1周期)",
    "keep shuffling a bag of the 7 tetrominoes": "テトロミノ7種類が1巡ごとに均等に配給されます (標準ガイドライン)",
    "14-BAG": "14-BAG (14種1周期)",
    "keep shuffling a bag of 2x the 7 tetrominoes": "7種類のミノが各2個ずつ（計14個）入ったバッグから配給されます",
    "7+1-BAG": "7+1-BAG (7種+1個)",
    "keep shuffling a bag of the 7 tetrominoes with one random extra tetromino": "基本の7種に、ランダムな1個を加えた計8個単位で配給されます",
    "7+2-BAG": "7+2-BAG (7種+2個)",
    "keep shuffling a bag of the 7 tetrominoes with two random extra tetrominoes": "基本の7種に、ランダムな2個を加えた計9個単位で配給されます",
    "7+X-BAG": "7+X-BAG (ランダム追加)",
    "keep shuffling a bag of the 7 tetrominoes. the first few bags contain a few extras.": "基本の7種に、序盤のバッグへ追加ミノが混ざる変則ルールです",
    "random with repetition protection": "同じミノが極端に連続しない補正付き完全ランダム",
    "PAIRS": "ペア (2種限定)",
    "alternate between 2 tetrominoes": "2種類のミノだけが交互に流れ続ける偏った配給です",
    "TOTAL MAYHEM": "カオス (完全ランダム)",
    "completely random generation": "なんの補正もない完全ランダム配給です",
    "— interested in playtesting something new for TETR.IO?": "- TETR.IOのテストプレイに参加してみませんか？",
    "Apply now": "今すぐ応募する",
    "You are currently not a supporter.": "現在サポーターではありません。",
    "Become a supporter or gift supporter status today and directly support TETR.IO development!": "サポーターになるか、フレンドにサポーターを贈ってTETR.IOの開発を直接支援しましょう！",
    "LOG OUT ALL": "すべての端末からログアウト",
    "REMOVE": "削除",
    "CHANGE": "変更",
    "AVATAR": "アバター画像",
    "a nice, 2MB max. image to represent yourself, or a generic identicon if none is chosen.": "あなたを表す最大2MBまでの画像。設定しない場合は自動生成アイコンになります。",
    " No avatar set": " アバター未設定",
    "BANNER": "プロフィールバナー",
    "SUPPORT OR GIFT": "サポーターになる / 贈る",
    " No banner set": " バナー未設定",
    "CONFIG / ACCOUNT": "設定 / アカウント",
    "ǹ REMOVE": "ǹ 削除",
    "ǹ CHANGE": "ǹ 変更",
    "ABOUT ME": "自己紹介",
    "ǹ SAVE": "ǹ 保存",
    "Write something...": "ひとことメッセージを入力…",
    " Korea, Republic of": " 大韓民国",
    "ORDER HISTORY": "注文履歴",
    "view previous orders": "過去の購入履歴を確認",
    "PRIVACY": "プライバシー",
    "show total time played on my profile": "プロフィールに総プレイ時間を表示",
    "show # of online games won on my profile": "プロフィールにオンライン勝利数を表示",
    "show # of online games played on my profile": "プロフィールにオンライン対戦数を表示",
    "show my country on my profile": "プロフィールに国籍を表示",
    "WHO CAN ADD ME AS FRIEND": "フレンド申請を許可する範囲",
    "This does not apply retroactively.": "過去に登録されたフレンドには影響しません。",
    "MY FRIENDS": "フレンドのみ",
    "EVERYONE": "誰でも許可",
    "WHO CAN SEE WHETHER I'M ONLINE": "オンライン状態の公開範囲",
    'e.g. "Online", "Away", "Offline". People who cannot see whether you\'re online cannot invite you to rooms either.': '例: 「オンライン」「離席中」「オフライン」。あなたのオンライン状態が見えないユーザーは、あなたを部屋に招待することもできません。',
    "NOBODY": "許可しない (自分のみ)",
    "WHO CAN SEE WHAT I'M DOING": "プレイ中の状態の公開範囲",
    'e.g. "Playing 40 LINES", "In TETRA LEAGUE queue", "In Menus"': '例: 「40 LINESプレイ中」「TETRA LEAGUE待機中」「メニュー画面」',
    "WHO CAN SEE WHAT ROOM I'M IN": "参加中ルームの公開範囲",
    'e.g. "In QUICK PLAY lobby", "In a public custom room". People who can see what room you\'re in can also quickly join said room. Private rooms are always hidden.': '例: 「QUICK PLAYロビー」「公開カスタムルーム」。滞在中の部屋が見えるユーザーは、直接その部屋に参加できます（非公開ルームは常に隠されます）。',
    "WHO CAN SEND ME DIRECT MESSAGES": "ダイレクトメッセージ(DM)の受信範囲",
    "Direct messages from non-friends show up on the NON-FRIENDS tab in the social overlay.": "フレンド以外からのメッセージは、ソーシャル画面の「フレンド以外」タブに振り分けられます。",
    "WHO CAN SEND ME INVITES TO ROOMS": "部屋への招待を受け取る相手",
    "To be able to send you an invite, others will also need to be able to see whether you're online.": "招待を受け取るには、相手に対してオンライン状態が公開されている必要があります。",
    "this is the name you will show up to others as.": "他プレイヤーに表示されるあなたの名前です。",
    "EMAIL": "メールアドレス",
    "this email account will be used for secure account actions, like account recovery.": "パスワード復旧などのセキュリティ手続きに使用されます。",
    "you do not currently have an email set. if you lose your password, your account cannot be recovered!": "現在メールアドレスが設定されていません。パスワードを忘れた場合、アカウントの復旧が不能になります！",
    "you can change the password used to log in here.": "ログイン用パスワードを変更できます。",
    "TWO-FACTOR AUTHENTICATION": "2段階認証 (2FA)",
    "ENABLE": "有効化",
    "CONNECTIONS": "連携アカウント",
    "link other accounts with TETR.IO here, or remove them at any time.": "他のサービスのアカウントをTETR.IOに連携・解除できます。",
    "display publicly": "プロフィールに公開する",
    "delete my account": "アカウントを削除",
    "CONFIG / ACCOUNT / ORDERS": "設定 / アカウント / 注文履歴",
    "view past orders for your account": "過去の決済・サポーター購入履歴を確認できます",
    "Need help?": "お困りですか？",
    "This page will guide you through the most common problems": "よくある不具合や解決策のガイドです",
    "See something out of the ordinary?": "不審な点を見つけましたか？",
    "Status": "ステータス",
    "Description": "内容",
    "Price (excluding taxes and fees)": "価格 (税抜・手数料抜)",
    "Payment total (including taxes and fees)": "合計支払額 (税込)",
    "Transaction number": "取引番号",
    "Merchant": "販売元",
    "Created": "作成日時",
    "Last updated": "最終更新日",
    "PENDING": "処理中",
    "(unknown)": "(不明)",
    "(not paid yet)": "(未払い)",
    "REMOVE AVATAR": "アバターを削除",
    "remove your avatar? it'll be replaced by a generic identicon.": "アバター画像を削除しますか？自動生成のデフォルトアイコンに戻ります。",
    "PASSWORD REQUESTED": "パスワードが必要です",
    "you must enter a new password": "新しいパスワードを入力してください",
    "support development or gift supporter status and get rewards!": "開発を支援したりサポーター権限を贈って特典を手に入れよう！",
    "get the desktop client for extra functions and improved performance": "より高いパフォーマンスと拡張機能を利用できるデスクトップ版アプリを入手しよう",
    "PATCH NOTES": "パッチノート",
    "follow development and see what's new": "開発の進捗や新機能を確認する",
    "COMMUNITY DISCORD": "公式 コミュニティ DISCORD",
    "DEVELOPER BLOG": "開発者ブログ",
    "ISSUE TRACKER": "バグ・要望トラッカー",
    "MUSIC ROOM": "ミュージックルーム (BGM試聴)",
    "JOIN HARD DROP": "HARD DROP コミュニティに参加",
    "join an extensive, vibrant community about all things stacker": "世界最大のパズルゲームコミュニティ「Hard Drop」に参加しましょう",
    "LEGAL & ABOUT": "利用規約 & 概要",
    "GET SUPPORT": "サポートを受ける",
    "a connection error has occured and the connection was closed unexpectedly.": "通信エラーが発生し、接続が切断されました。",
    "check your internet connection and configuration.": "インターネット接続やルーターの設定を確認してください。",
    "REASON: ribbon expired": "理由: 接続トークン(Ribbon)の期限切れ",
    "if you are certain this error is not on your side, please report it.": "ご自身の環境に問題がないと思われる場合は報告をお願いします。",
    " online now": " 人がオンライン",
    " has come online": " がオンラインになりました",
    " Away": " 離席中",
    " Busy": " 取り込み中",
    " Offline": " オフライン",
    " Not a friend": " フレンドではありません",
    " Blocked": " ブロック済み",
    "Achievement get!": "実績獲得！",
    "Please be civil. Staff will never ask for your credentials.": "マナーを守って会話しましょう。運営スタッフがパスワードを聞くことは絶対にありません。",
    "PROFILE": "プロフィール",
    "GIFT": "ギフトを送る",
    "this is your first game this week, play more to track your improvement": "今週最初のプレイです。繰り返しプレイして上達を記録しましょう",
    "this is your first game, play more to track your improvement": "初めてのプレイです！たくさん遊んで腕前を上げていきましょう",
    "LEAVE CURRENT GAME?": "試合を退出しますか？",
    "you're still in game. abandon the current game?": "まだ試合が進行中です。対戦を放棄して退出しますか？",
    "LEAVE": "退出する",
    "Disconnected": "切断されました",
    "MATCH SUSPENDED": "試合一時中断",
    "Your opponent has disconnected, but may still return.": "対戦相手の接続が切れました。相手の再接続を待っています。",
    "You will gain points as you wait. If your opponent does not return, you win by default.": "待機中に少しずつポイントが加算されます。相手が戻らない場合、不戦勝となります。",
    "RESUMING MATCH": "試合を再開しています",
    "YOU MUST RETURN TO YOUR MATCH": "対戦へ復帰してください",
    "Abandon Match": "試合を棄権（無効試合化）する",
    "The match will be declared No Contest.": "この対戦は無効試合（ノーコンテスト）として処置されます。",
    "No player will be penalized, no player will gain or lose TR.": "双方にペナルティは発生せず、TRの変動もありません。",
    "I'm fine with that": "同意する",
    "NEXT POINT IN ": "次の加算ポイントまで ",
    "VICTORY IN ": "勝利判定まで ",
    "BOT": "BOT",
    "this is a known bot. all bots must have this tag, or it and its owners will be permanently banned.": "認定済みの対戦BOTです。すべてのBOTはこのタグの付与が義務付けられています。",

    "COUNTRY RANK": "国内順位",
    "GLOBAL RANK": "世界順位",

    "Enjoyed Duo?": "Duoモードは楽しめましたか？",

    "THIS TETR.IO CLIENT HAS BEEN MODIFIED": "※ 改造されたTETR.IOクライアントが検出されました",
    "Third-party modifications to TETR.IO are not supported by the TETR.IO team and may have compatibility, performance and safety issues.": "第三者によるMODや改造版は公式のサポート対象外であり、動作不良や安全上の問題を引き起こす可能性があります。",
    "Do not report any issues while using third-party modifications. Modifications that alter gameplay are strictly forbidden.": "MOD使用中の不具合報告はお控えください。なお、対戦ルールやゲーム性を変化させる改造は固く禁止されています。",
    "This message will disappear after 10 seconds": "このメッセージは10秒後に自動的に消えます",

    "you are using the desktop client! this means you can:": "デスクトップ版アプリをご利用中です！以下の機能が使えます:",
    "• hit F11 to go FULL SCREEN": "• F11 キーでフルスクリーン表示切り替え",
    "• hit CTRL+SHIFT+I to open the CONSOLE": "• Ctrl + Shift + I でデベロッパーコンソールを開く",
    "as well as edit options you see below": "その他、下記の各種専用オプションの設定変更",

    "SKIP LOGIN SCREEN": "ログイン画面をスキップ",
    "NEVER": "スキップしない",
    "WHEN NEEDED": "必要な時のみ",
    "ALWAYS": "常にスキップ",
    "enable HARD VSYNC": "ハードウェア垂直同期 (VSync) を有効化",
    "FRAMERATE LIMITER": "フレームレート制限",
    "install updates automatically if possible": "アップデートを自動でインストール",
    "enable DISCORD RICH PRESENCE": "Discord Rich Presence を有効化",
    "flash taskbar icon": "マッチ完了時にタスクバーアイコンを点滅",
    "streamer compatibility mode (slow!)": "配信者向け互換モード (動作が重くなります)",
    "disable third-party advertisements": "サードパーティ広告を無効化",
    "EXIT TETR.IO?": "TETR.IO を終了しますか？",

    "career best ": "自己ベスト ",

    "TETR.IO DESKTOP should open soon!": "TETR.IO デスクトップアプリが起動します…",
    "you can close this tab once it has opened": "アプリが起動したら、このブラウザタブは閉じて構いません",

    "FATIGUE SETS IN…": "疲労が蓄積していく…",
    "+2 PERMANENT LINES": "＋2ライン (消去不可)",
    "YOUR BODY GROWS WEAK…": "体が衰弱していく…",
    "receive 25% more garbage": "受けるおじゃま量が25%増加",
    "ALL SENSES BLUR TOGETHER…": "すべての感覚が薄れていく…",
    "+3 PERMANENT LINES": "＋3ライン (消去不可)",
    "YOUR CONSCIOUSNESS FADES…": "意識が遠のいていく…",
    "THIS IS THE END.": "これで終わりだ。",
    "+5 PERMANENT LINES": "＋5ライン (消去不可)",

    "i'm a grinch (disable most holiday cheer)": "ホリデー演出を無効化（グリンチモード）",
    "add salt to the board (prevent snow accumulating on it)": "盤面に塩を撒く（雪の積もりを防止）",
    "snow in the menus": "メニュー画面に雪を降らせる",
    "SNOWSTORM": "吹雪エフェクト",
};

/**
 * @type {[string, RegExp, string][]}
 */
const SELECTOR_TRANSLATIONS = [
    ["#footer_text", "#footer_text", /welcome to (.*?)!/, "$1へようこそ！"],
    ["#sig_config > p", "#sig_config", /tweak your&nbsp;(.*?)&nbsp;experience/, "$1の体験を調整"],
    ["#sig_about > p", "#sig_about", /all about&nbsp;<span class="cheeky">(.*?)<\/span>(.*)/, "<span class=\"cheeky\">$1</span>$2のすべて"],
    ["#footer_text", "#footer_text", /tweak your settings for a better (.*?) experience/, "より快適な$1体験のために設定を調整"],
    ["#config_export > p", "#config_export", /download a .TTC file of your config you can drag into&nbsp;(.*?)&nbsp;to import/, "$1にドラッグして読み込める .TTC 設定ファイルをダウンロード"],
    ["#video_powersave", "#video_powersave", /make&nbsp;(.*?)&nbsp;run slowly to keep other programs running smoothly/, "他のプログラムをスムーズに動かすため $1 の動作を低速化"],
    ["#sys_guide > h2", "#sys_guide", /welcome to&nbsp;(.*?)!/, "$1へようこそ！"],
    [".scroller_block > h2", ".scroller_block", /welcome to&nbsp;(.*?)!/, "$1へようこそ！"],
    ["#sys_guide > p", "#sys_guide", /(.*?)&nbsp;is a free familiar yet fast-paced online stacker in the same genre as tetris, and played by millions across the globe./, "$1はテトリスと同ジャンルの親しみやすくスピーディーな無料オンラインスタッカーで、世界中の何百万もの人々にプレイされています。"],
    [".scroller_block > p", ".scroller_block", /(.*?)&nbsp;is a free-to-win familiar yet fast-paced online stacker in the same genre as tetris, and played by millions across the globe./, "$1は世界中の何百万もの人々にプレイされている、無料で楽しめるテトリスと同ジャンルの親しみやすくスピーディーなオンラインスタッカーです。"],
    ["#footer_text", "#footer_text", /thank you for playing (.*?)!/, "$1をプレイしていただきありがとうございます！"],
    //["#a.electron_jump_also.ns", /get&nbsp;(.*?)&nbsp;DESKTOP/, "$1 デスクトップ版を入手"],
    //["#div.electron_jump.ns", /open in&nbsp;(.*?)&nbsp;DESKTOP/, "$1 デスクトップ版で開く"],
    ["#about_desktop > h1", "#about_desktop", /(.*?)&nbsp;DESKTOP/, "$1 デスクトップ"],
    ["#enter_matchmaking > p", "#enter_matchmaking", /(.*?) CLICK TO CANCEL/, "$1 クリックでキャンセル"],
    ["#waterfall > div > p", "#waterfall", /(.*?) ko'd by ((.*?)*)/, "$1が$2によってKO"],
    ["#waterfall > div > p", "#waterfall", /ko'd by ((.*?)*)/, "$1によってKO"],
    ["#waterfall > div > p", "#waterfall", /ko'd ((.*?)*)/, "$1をKO"],
    ["#zenith_deck_infos > div > p", "#zenith_deck_infos", /reach floor (.*?) to unlock/, "$1階到達でアンロック"],
    [".rank_sub", ".rank_sub", /TOP (.*?)%/, "上位 $1%"],
    [".rank_sub", ".rank_sub", /(.*?) improvement • last PB was (.*?) ago/, "$1 更新 • 前回の自己ベストは $2 前"],
    [".rank_sub", ".rank_sub", /(.*?) behind • last PB was (.*?) ago/, "$1 遅れ • 前回の自己ベストは $2 前"],
    [".menuslide_rollup", ".menuslide_rollup", /SPECTATE ((.*?)*)/, "$1 を観戦"],
    ["#footer_text", "#footer_text", /change settings in your (.*?) account/, "$1 アカウントの設定を変更"],
    ["#about_supporter > h1", "#about_supporter", /^support&nbsp;(.*?)$/gi, "$1 を支援"],
    [".notification > p", "#notifications", /The Duo mod is a <b>TETR.IO Supporter-only feature<\/b> — one of the two players needs Supporter.<br><b>(.*?)<\/b> paid for you this time, but if you want to play Duo with someone who doesn't have Supporter yet, why not <b>help support the game<\/b> and pick some up\?/, "Duoモードは<b>TETR.IOサポーター限定機能<\/b>です — 2人のうちどちらか1人がサポーターである必要があります。<br>今回は<b>$1<\/b>が負担してくれましたが、まだサポーターになっていないフレンドとDuoを遊ぶなら、ぜひ<b>開発を支援して<\/b>サポーターになりませんか？"],
    ["#registeralt_form", "#registeralt_form", /are you&nbsp;(.*?)\?/, "$1 で間違いありませんか？"],
    ["#registeralt_form > p", "#registeralt_form", /TETR.IO has a policy of&nbsp;<b>one account per person \(anonymous accounts excluded\)<\/b>. making multiple accounts may result in permanent restriction of all your accounts./, "TETR.IOでは<b>1人1アカウント（匿名アカウントを除く）<\/b>の利用規約を設けています。複数アカウントの作成は、所有する全アカウントの永久利用停止措置につながる場合があります。"],
    ["#registeralt_form > .modal_also", "#registeralt_form", /read the&nbsp;<a href="\/about\/rules\/#ap" target="_blank">full policy<\/a>&nbsp;for more info. in doubt, or if you believe your usage of a second account is justified, please&nbsp;<a href="\/about\/support\/" target="_blank">contact support<\/a>./, '詳細については&nbsp;<a href="/about/rules/#ap" target="_blank">利用規約全文</a>&nbsp;をご確認ください。ご不明な点がある場合や、サブアカウントの使用に正当な理由があるとお考えの場合は、<a href="/about/support/" target="_blank">サポートまでお問い合わせ</a>&nbsp;ください。'],
    [".ig_chat_message > p", "#ingame_chat_container", /Welcome to Quick Play chat! Please remember to be civil to your opponents - chat is actively monitored.\n\nThis chat is linked with (.*?)our Discord server<\/a>\./, "クイックプレイのチャットへようこそ！対戦相手へのマナーを守って会話しましょう（チャットは監視されています）。\n\nこのチャットは $1公式 Discord サーバー</a> と連携しています。"],
    [".notification > p", "#notifications", /changing (.*?) requires a restart to go in effect. hit F5 on your keyboard to restart\./, "$1 の変更を適用するには再起動が必要です。キーボードの F5 を押して再起動してください。"],
    [".notification > p", "#notifications", /changing (.*?) requires a restart to fully go in effect. hit F5 on your keyboard to restart\./ , "$1 の変更を完全に適用するには再起動が必要です。キーボードの F5 を押して再起動してください。"],
    ["#referee_top, #roommodeblurb, #scoreslide_header", "#referee_top, #roommodeblurb, #scoreslide_header", /VERSUS ((.*?)*)/, "対戦 $1"],
    ["#referee_top, #roommodeblurb, #scoreslide_header", "#referee_top, #roommodeblurb, #scoreslide_header", /TETRA LEAGUE ((.*?)*)/, "TETRA LEAGUE $1"],
    ["#referee_top, #roommodeblurb, #scoreslide_header", "#referee_top, #roommodeblurb, #scoreslide_header", /(.*?) FT((.*?)*)/, "$1 $2勝先取"],

    ["#config_electron > h1", 'div[data-menuview="config"]', /(.*?)&nbsp;DESKTOP/, "$1 デスクトップ"],
    ["#config_electron > p", 'div[data-menuview="config"]', /change settings for&nbsp;(.*?)&nbsp;DESKTOP/, "$1&nbsp;デスクトップ設定の変更"],
    ["#header_text", "#header_text", /CONFIG \/ (.*?) DESKTOP/, "設定 / $1 デスクトップ"],
    ['div[data-menuview="config_electron"] > .scroller_block > .ns', 'div[data-menuview="config_electron"]', /• hit F5 to reload&nbsp;((.*?)*)/, "• F5 を押して $1 を再読み込み"],
    ['div[data-menuview="config_electron"] > .scroller_block > .ns', 'div[data-menuview="config_electron"]', /(.*?)&nbsp;DESKTOP V(.*?)/, "$1&nbsp;デスクトップ V$2"],
    ["#footer_text", "#footer_text", /change (.*?) DESKTOP settings/, "$1 デスクトップ設定の変更"],

    ["#social_relationships > div > p, #social_dm_status", "#social_relationships, #social_dm_status", /In ((.*?)*)/, "$1 に滞在中"],
    ["#social_relationships > div > p, #social_dm_status", "#social_relationships, #social_dm_status", /Spectating ((.*?)*)/, "$1 を観戦中"],
    ["#social_relationships > div > p, #social_dm_status", "#social_relationships, #social_dm_status", /Ending ((.*?)*)/, "$1 を終了中"],
    ["#social_relationships > div > p, #social_dm_status", "#social_relationships, #social_dm_status", /Playing ((.*?)*)/, "$1 をプレイ中"],
    ["#social_relationships > div > p, #social_dm_status", "#social_relationships, #social_dm_status", /Found ((.*?)*)/, "$1 を検出"],
    ["#social_status", "#social_status", /In (.*?) <img/, "$1 に滞在中 <img"],
    ["#social_status", "#social_status", /Spectating (.*?) <img/, "$1 を観戦中 <img"],
    ["#social_status", "#social_status", /Ending (.*?) <img/, "$1 を終了中 <img"],
    ["#social_status", "#social_status", /Playing (.*?) <img/, "$1 をプレイ中 <img"],
    ["#social_status", "#social_status", /Found (.*?) <img/, "$1 を検出 <img"],

    [".chat_embed_ally", "#ingame_chat_container", /together with ((.*?)*)/, "$1 と共にプレイ"],
    ["#zenith_zenithtimer, #tetra_zenithtimer, #zenithresults_zenithtimer", "#zenith_zenithtimer, #tetra_zenithtimer, #zenithresults_zenithtimer", /LEADERBOARD CYCLED (.*?) AGO/, "<p class='BMHANNAAirDMJ'>$1 前にリーダーボード更新完了</p>"],
    ["#zenith_zenithtimer, #tetra_zenithtimer, #zenithresults_zenithtimer", "#zenith_zenithtimer, #tetra_zenithtimer, #zenithresults_zenithtimer", /LEADERBOARD CYCLES IN ((.*?)*)/, "<p class='BMHANNAAirDMJ'>あと $1 でリーダーボード更新</p>"],
    ["#dialogs > .tetra_modal > h3", "#dialogs", /JOINED (.*?) AGO/, "<p class='BMHANNAAirDMJ'>$1 前に登録</p>"],
    
    ["#footer_text", "#footer_text", /(.*?) played by (.*?) on ((.*?)*)/, "$3 に $2 がプレイした $1"],
    ["#footer_text", "#footer_text", /(.*?) versus (.*?) played on ((.*?)*)/, "$3 にプレイされた $1 vs $2"],
    ["#footer_text", "#footer_text", /プレイした 40 LINES/, "プレイした 40 LINES"],
    ["#footer_text", "#footer_text", /プレイした BLITZ/, "プレイした BLITZ"],
    ["#footer_text", "#footer_text", /プレイした QUICK PLAY/, "プレイした クイックプレイ"],
    ["#footer_text", "#footer_text", /プレイした EXPERT QUICK PLAY/, "プレイした エキスパート クイックプレイ"],
    ["#tetra_myrecords > .record_item > .record_owner", "#tetra_myrecords", /tetra league ((.*?)*)/, "TETRA LEAGUE $1"],
    ["#tetra_myrecords > .record_item > .record_result", "#tetra_myrecords", /ÿòìýøûĂ ((.*?)*)/, '<span style="font-size:30px"><b>勝利</b></span> $1'],
    ["#tetra_myrecords > .record_item > .record_result", "#tetra_myrecords", /íîïîêý ((.*?)*)/, '<span style="font-size:30px"><b>敗北</b></span> $1'],
    ["#supporter_payment_price > div", "#supporter_payment_price > div", /(.*?) months?/, "$1ヶ月"],
]

// CSS 폰트 적용
const fontFace = `
    @import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard-jp.min.css");
  
    @font-face {
      font-family: 'BMHANNAAir';
      src: url('./fonts/Tanugo-TTF-Round-Regular.woff2') format('woff2');
      font-weight: normal;
      font-style: normal;
    }
    @font-face {
      font-family: 'BMHANNAAirDMJ';
      src: url('./fonts/Tanugo-TTF-Round-Regular.woff2') format('woff2');
      font-weight: normal;
      font-style: normal;
      size-adjust: 110%;
    }
  
    @font-face {
          font-family: 'Orbit-Regular';
      src: url('./fonts/Tanugo-TTF-Regular.woff2') format('woff2');
      font-weight: normal;
      font-style: normal;
    }
  
   
  
    .replayid::before {
      font-family: 'HUN', 'BMHANNAAir' !important;
      content: "리플레이 ID:" !important;
    }

    #config_account_supporter_bar {
        font-family: 'C', 'Pretendard JP' !important;
    }

    .BMHANNAAirDMJ {
        display: inline;
        font-family: 'HUN', 'BMHANNAAirDMJ';
    }
    .player_count.room_count::before {
        content: '방' !important;
        margin-right: 0.2em !important;
        font-size: .6em !important;
        color: #fffA !important;
    }
    .player_count.room_count::after {
        content: '개' !important;
    }
  `;

const style = document.createElement('style');
style.type = 'text/css';
style.appendChild(document.createTextNode(fontFace));
document.head.appendChild(style);

function replaceFontFamily(element) {
    if (element.nodeType === Node.ELEMENT_NODE) {
        const computedStyle = window.getComputedStyle(element);
        const fnt = computedStyle.fontFamily.trim();
        if (fnt === 'HUN' && !element.matches('#now_playing_jp')) {
            element.style.fontFamily = `'HUN', 'BMHANNAAir'`;
        }
        if (fnt === 'PFW') {
            element.style.fontFamily = `'PFW', 'Orbit-Regular'`;
        }
        if (fnt === 'PFW, sans-serif') {
            element.style.fontFamily = `'PFW', 'Orbit-Regular'`;
        }
        if (fnt === 'C' || fnt == '"C"') {
            element.style.fontFamily = `'C', 'Pretendard JP'`;
        }
    }
}

function traverseAndReplaceFonts(node) {
    replaceFontFamily(node);
    node.childNodes.forEach(childNode => {
        traverseAndReplaceFonts(childNode);
    });
}

function isBlacklisted(node) {
    // 노드가 .chat_message.ig_chat_message.roomownerchat을 포함하고 있는지 확인
    // 노드가 .chat_message.system p를 포함하고 있지 않은 경우에만 블랙리스트 처리
    if (node.matches(".chat_message.ig_chat_message.roomownerchat")) {
        // 노드가 .chat_message.system p 자손을 포함하는 경우 블랙리스트 처리하지 않음
        if (node.querySelector(".chat_message.system p")) {
            return false;
        }
        return true;
    }
    // 노드가 퀵플레이 leaderboard 안에 있는 유저네임이면 블랙리스트 처리
    if (node.matches(".rssp_username, .rssp_username_longduo")) {
        return true;
    }
    // 노드가 테트라 리그 매칭 화면에 있는 유저네임이면 블랙리스트 처리
    if (node.matches("#pair_name_p1, #pair_name_p2")) {
        return true;
    }
    // 노드가 테트라 리그 점수 화면에 있는 유저네임이면 블랙리스트 처리
    if (node.matches("#waitstate_a_username, #waitstate_b_username")) {
        return true;
    }
    // 노드가 유저 정보창에 있는 유저네임이면 블랙리스트 처리
    if (node.matches(".tetra_modal>.avatar+h2")) {
        return true;
    }
    // 노드가 우측 상단 프로필에 있는 유저네임이면 블랙리스트 처리
    if (node.matches("#me_username")) {
        return true;
    }
    // 아 이젠 쓰기도 귀찮네 대충 방
    if (node.matches(".scroller_player>h1")) {
        return true;
    }
    // 소셜
    if (node.matches(".social_relationship > h1 > span, #social_dm_username")) {
        return true;
    }

    // 방이름
    if (node.matches("#room_listing_name, #room_content_name")) {
        return true;
    }

    // 리더보드 유저 이름
    if (node.matches(".record_owner")) {
        return true;
    }
    return false;
}

function translateNode(node) {
    if (node.nodeType === Node.ELEMENT_NODE) {
        // 블랙리스트에 포함된 노드 건너뛰기
        if (isBlacklisted(node)) {
            return;
        }

        // .chat_message.ig_chat_message 요소 필터링 (다른 클래스가 없는 경우)
        if (node.matches(".chat_message.ig_chat_message") && node.classList.length === 2) {
            return;
        }
    }

    if (node.nodeType === Node.TEXT_NODE) {
        // 텍스트 노드에서도 블랙리스트 검사
        if (node.parentNode != null && isBlacklisted(node.parentNode)) {
            return;
        }
        let text = node.textContent;
        let trimmedText = text.trim();
        // 원본 텍스트를 확인하여 앞뒤 공백을 유지
        if (TRANSLATIONS[text]) {
            node.textContent = TRANSLATIONS[text];
        } else if (TRANSLATIONS[trimmedText]) {
            node.textContent = text.replace(trimmedText, TRANSLATIONS[trimmedText]);
        }
    } else if (node.nodeType === Node.ELEMENT_NODE) {
        if (node.tagName === 'INPUT' && node.getAttribute('placeholder')) {
            let placeholderText = node.getAttribute('placeholder');
            let trimmedPlaceholder = placeholderText.trim();
            if (TRANSLATIONS[placeholderText]) {
                node.setAttribute('placeholder', TRANSLATIONS[placeholderText]);
            } else if (TRANSLATIONS[trimmedPlaceholder]) {
                node.setAttribute('placeholder', placeholderText.replace(trimmedPlaceholder, TRANSLATIONS[trimmedPlaceholder]));
            }
        }
        node.childNodes.forEach(childNode => {
            translateNode(childNode);
        });
    }
}


async function translatePage() {
    document.querySelectorAll('body *').forEach(node => {
        translateNode(node);
    });
    for (const [selector, detectSelector, regex, replace] of SELECTOR_TRANSLATIONS) {
        const targetElements = document.querySelectorAll(selector);

        for (var targetElement of targetElements) {
            if (targetElement == null) continue;
            const html = targetElement.innerHTML;
            if (html in TRANSLATIONS) continue;
            if (regex.test(html)) {
                targetElement.innerHTML = html.replace(regex, replace);
            }
        }
    }
    for (var jptxt of parser(".jp_kana")()) {
        jptxt.style.fontFamily = `'HUN'`;
    }

}




const observer = new MutationObserver(mutations => {
    mutations.forEach(async mutation => {

        if (mutation.type === 'childList') {
            mutation.addedNodes.forEach(node => {
                translateNode(node);
                requestAnimationFrame(() => traverseAndReplaceFonts(node));  // 새로 추가된 노드에도 폰트 적용
            });
        }
    });
});

// body 요소에서 자손을 포함한 모든 변경 사항을 감시
observer.observe(document.body, { childList: true, subtree: true });

for (const [selector, detectSelector, regex, replace] of SELECTOR_TRANSLATIONS) {
    var sel = document.querySelectorAll(detectSelector);
    if (sel == null) continue;
    var obs = new MutationObserver(mutations => {
        (async () => {
            //console.log(sel);
            const targetElements = document.querySelectorAll(selector);

            for (var targetElement of targetElements) {
                if (targetElement == null) continue;
                const html = targetElement.innerHTML;
                if (html in TRANSLATIONS) continue;
                if (regex.test(html)) {
                    targetElement.innerHTML = html.replace(regex, replace);
                }
            }
        })();
    });
    
    /*console.log("translate target:");
    console.log(sel);*/
    for (var s of sel) {
        obs.observe(s, { childList: true, subtree: true });
    }
}
// 페이지 로드 시 폰트 교체 및 번역 실행
/*window.onload = function() {
  requestAnimationFrame(() => {
    document.querySelectorAll('body *').forEach(element => {
      replaceFontFamily(element);
    });
    translatePage();
  });
};*/
requestAnimationFrame(() => {
    document.querySelectorAll('body *').forEach(element => {
        replaceFontFamily(element);
    });
    translatePage();
});
